### ISSUE TITLE
Achieving performance

### ISSUE THREAD

**Issue by Raggaer** [yuin/gopher-lua#100]
Im trying to achieve some performance improvements using gopher-lua. I am using gopher-lua to let users write lua code to handle HTTP requests.

Instead of calling `DoFile` on each request I tried the following:

- Call `LoadFile` on every lua file of my application and store them on a `map[string]*lua.LFunction`
- Get a state from a pool and call `Push` and `PCall`

I guess this way I dont open the lua file on each request. But it seems that calling `PCall` is not thread-safe? I am getting data-race erros on `PCall`

Is this a good way to achieve more performance or `DoFile` is enough? I was running `pprof` at my application and the major work is when gopher-lua calls `yyParse` using lots of GB.

**Comment by Raggaer** [comment]
I see now that `LFunction` is not thread-safe

**Comment by bbuck** [comment]
I found the most performance gain by pooling states. The problem for me was the parsing/loading of states on demand. Instead I implemented a map of `filename->chan LState` and worked off of it this way.

**Comment by Raggaer** [comment]
That might be a good idea actually. Mind explaining it a little bit more? you call `DoFile` on your map states for each file?

Thanks

**Comment by Raggaer** [comment]
@bbuck how would you go leaving the states loaded and re-using them?

I tried `DoFile` and saving that state, then calling `state.Call` or `state.PCall` without success

**Comment by bbuck** [comment]
Here's my pool implementation: https://gist.github.com/bbuck/e99fff372aae33e2f412d9980cdae4ca

I've heavily wrapped `lua.LState` to make interactions simpler, but I've converted it to using `lua.LState`.

So the whole idea here is you create a pool with maximum number of states and a "StateMutator" function designed to "load" your states for usage as the Pool needs to generate more. It's a lazy pool, so if you say specify a maximum of `10` states, but only ever end up using 3, then only 3 get generated. The only note here is that one is generated up front, so the Pool is automatically seeded with one state run through the mutator. 

So sample usage goes like this:

```go
p := NewStatePool(2, func(L *lua.LState) {
	L.OpenLibs()
	L.DoString(`
        function greet(name)
            return "Hello, " .. name .. "!"
        end
    `)
})

s := p.Get()
defer s.Release()
err := s.CallByParam(lua.P{
	Fn:   s.GetGlobal("greet"),
	NRet: 1,
}, lua.LString("World"))
if err != nil {
	panic(err)
}
msg := s.CheckString(1)

fmt.Println(msg) // prints "Hello, World"
```

**Comment by Raggaer** [comment]
Thanks @bbuck 

With some changes thanks to your idea I achieved a lot of performance gains. This can now be closed I guess
