### ISSUE TITLE
Access local variable

### ISSUE THREAD

**Issue by Raggaer** [yuin/gopher-lua#101]
Hello, after doing `DoFile` how can I access a local variable?

`GetLocal` is not very intuitive. Thanks

**Comment by aduermael** [comment]
@Raggaer Did you find out ? I'm having the same issue... 🙂

**Comment by Raggaer** [comment]
@aduermael No success at all. Waiting for someone to enlighten us

**Comment by fiatjaf** [comment]
https://www.lua.org/pil/23.1.1.html
