### ISSUE TITLE
Bitwise operations

### ISSUE THREAD

**Issue by sp-ludovic-ivain** [yuin/gopher-lua#102]
Do you have any plan for supporting bitwise operations ?
http://lua-users.org/wiki/BitwiseOperators

**Comment by yuin** [comment]
No. GopherLua is a Lua5.1 implementation that does not include bitwise operations.
Of course, you can implement bitwise operations as a library :)

**Comment by sp-ludovic-ivain** [comment]
Thanks, i'll do it ! :)
