### ISSUE TITLE
Accessing lua object in go is somewhat awkward

### ISSUE THREAD

**Issue by gaffo** [yuin/gopher-lua#104]
There should be a function that more easily converts a set of lua objects into go space even if it's a bit daft.

**Comment by yuin** [comment]
Thanks for your suggestion, but I do not think so.
As I wrote in the issue template:

>> GopherLua is a Lua5.1 implementation. In Lua, to keep it simple, it is more important to remove functionalities rather than to add functionalities unlike other languages . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Your way of thinking is for other batteries-included languages like Ruby, Python, Java and so on.

Anyway, I've already created a library named [gluamapper](https://github.com/yuin/gluamapper), and [gluamapper.ToGoValue](https://godoc.org/github.com/yuin/gluamapper#ToGoValue) acts like this.

**Comment by gaffo** [comment]
Oh cool. I'll look at those
