### ISSUE TITLE
Shipping Lua code with an executable

### ISSUE THREAD

**Issue by technomancy** [yuin/gopher-lua#106]
I have a question about a practical recommendation for how to ship Lua code with your binary. During development I want to keep my Lua source in a separate file, but I'm not clear on how to include that Lua source inside my binary so it's included when the executable is deployed. It seems in order to do that I need the code to be a string inside a `.go` file, but this is very inconvenient during development.

Is there any recommended way to handle this? I suppose I could use a preprocessor and create a `.go` file containing strings from the `.lua` files, but I don't want to do that if there is a better way.

**Comment by Raggaer** [comment]
Have you tried to use https://github.com/jteeuwen/go-bindata ?

**Comment by technomancy** [comment]
I don't have binary data, just text. It looks like for text data that tool doesn't really buy you anything over using a preprocessor to create a `.go` file, so I will do that if there is no gopher-lua-specific way to solve it.

**Comment by yuin** [comment]
> Is there any recommended way to handle this? 
There is no recommended way.

**Comment by technomancy** [comment]
OK, thanks for letting me know.
