### ISSUE TITLE
incorrect unsafe usage

### ISSUE THREAD

**Issue by randall77** [yuin/gopher-lua#108]
You can't do
```
   var s string = ...
   var b []byte = *(*[]byte)(unsafe.Pointer(&s))
```
The pointer and length of the resulting slice are ok, but the capacity is junk.  Subsequent slicing of `b` will randomly fail.

This happens at github.com/yuin/gopher-lua/stringlib.go:365

See https://github.com/golang/go/issues/19284

**Comment by yuin** [comment]
@randall77 
\cc @TocarIP @dsnet

I have confirmed golang/go#19284.
Hmm, I'll give up this trick.

Anyway, I am anxious about whether same problem would happen in many go projects.
Of course I know this trick is "unsafe", but this trick has been widely used.
Actually, now I search "(*[]byte)(unsafe.Pointer" on github, then I get [44,836 go source results](https://github.com/search?utf8=%E2%9C%93&q=%22%28*[]byte%29%28unsafe.Pointer%22&type=Code&ref=searchresults).

**Comment by randall77** [comment]
I think your search is a bit too overbroad; not all matches are buggy.  But yes, paging through them reveals there are definitely some bad ones in there.

@adonovan: Is there any easy way to search for *(*[]byte)(unsafe.Pointer(&s)) where s is a string?

**Comment by yuin** [comment]
> I think your search is a bit too overbroad; not all matches are buggy. 

Yes I knew that. I'm searching this term for your reference.

By the way, I understand code like the following is still valid. Is this understanding of mine correct?

```go
func StringToBytes(s string) []byte {
	sh := (*reflect.StringHeader)(unsafe.Pointer(&s))
	bh := reflect.SliceHeader{sh.Data, sh.Len, 0}
	return *(*[]byte)(unsafe.Pointer(&bh))
}
```

**Comment by randall77** [comment]
A capacity of 0 is bad.  All slices should have `cap >= len`.  You probably want
```
bh := reflect.SliceHeader{sh.Data, sh.Len, sh.Len}
```
Otherwise looks ok.  But please take a close read of the godoc for `reflect.StringHeader` and `reflect.SliceHeader`; we're not guaranteeing they will work from one release to the next.

**Comment by yuin** [comment]
Ok, Thanks.
