### ISSUE TITLE
Switch to context from the standard lib

### ISSUE THREAD

**Issue by alicebob** [yuin/gopher-lua#109]
golang.org/x/net/context has moved into the standard library since Go 1.7 (1.8 is the current release). Switching to that package means projects using gopher-lua don't have to import the golang.org/x/net/context package anymore.

**Comment by yuin** [comment]
GopherLua currently supports >=Go1.6.
I'll do this at Go1.9 release.

golang.org/x/net/context has a fallback mechanism. If you use >=Go1.7, golang.org/x/net/context uses built int `context` package as its implementation.

**Comment by alicebob** [comment]
ok, thanks!
