### ISSUE TITLE
Sandbox environment

### ISSUE THREAD

**Issue by hugows** [yuin/gopher-lua#11]
Hi,

gopher-lua works great. I actually found out about it when Shopify announced its version (go-lua).
One thing I'd like to be able to do it to provide a sandbox environment for executing user scripts, e.g. preventing access to files and executing commands. Is this possible with gopher-lua?

Thanks!

**Comment by yuin** [comment]
Thanks for trying GopherLua out.
You can achieve sandbox environments with codes such as the following.

```go
import (
	"fmt"
	"github.com/yuin/gopher-lua"
)

func DoScriptInSandbox(L *lua.LState, script string) error {
	io := L.GetGlobal("io").(*lua.LTable)
	orgopen := io.RawGetH(lua.LString("open"))
	defer io.RawSetH(lua.LString("open"), orgopen)
	sandboxfunc := L.NewFunction(func(L *lua.LState) int {
		L.RaiseError("can not call in a sandbox environment.")
		return 0
	})
	io.RawSetH(lua.LString("open"), sandboxfunc)
	err := L.DoString(script)
	return err
}

func main() {
	L := lua.NewState()
	script := `
      local fp = assert(io.open("test.tx"))
      fp:close()
    `
	if err := DoScriptInSandbox(L, script); err != nil {
		fmt.Println(err.Error())
	}
	if err := L.DoString(script); err != nil {
		fmt.Println(err.Error())
	}
}

```

**Comment by Lua12138** [comment]
Is there any way to limit `Lua Code` memory usage and network usage?

For example, if the allocated memory is more than 32M, the program ends.
