### ISSUE TITLE
call loadfile in lua code fail

### ISSUE THREAD

**Issue by fastfading** [yuin/gopher-lua#112]
- [x] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [x] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : 
newest version from git pull
2. What version of Go are you using? : 
1.7
3. What operating system and processor architecture are you using? :
OS X
4. What did you do? :
go call lua script main.lua  in main.lua use loadfile("select.lua") function
5. What did you expect to see? :
loadfile properly
6. What did you see instead? :
it pop error like below ,  all path are right
panic: script/main.lua:46: script/select.lua line:1(column:1) near '?':   Invalid token

stack traceback:
	[G]: in function 'assert'
	script/main.lua:46: in main chunk
	[G]: ?

goroutine 1 [running, locked to thread]:
panic(0x4406f00, 0xc420180dc0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
	/Users/huzhang2/git/ikemen_go/src/main.go:123 +0xa44

**Comment by fastfading** [comment]
if i move the select.lua code into main.lua   gopher-lua runs ok

**Comment by yuin** [comment]
select.lua might start with [BOM](https://en.wikipedia.org/wiki/Byte_order_mark). GopherLua does not support BOM.

**Comment by fastfading** [comment]
thank u  ,  just like u said .  it is the bom issue


2017-03-27 11:49 GMT+08:00 Yusuke Inuzuka <notifications@github.com>:
