### ISSUE TITLE
A big memory take of on luatable！

### ISSUE THREAD

**Issue by yu321chang** [yuin/gopher-lua#117]
When i define a table in a lua file exp:
```

       local test = {}
       test[10000000] = {}
```

and load this file
it toke 600M+ memory after DoFile().

I follow the code and find this :
```
func (tb *LTable) RawSet(key LValue, value LValue) {
	switch v := key.(type) {
	case LNumber:
		if isArrayKey(v) {
			if tb.array == nil {
				tb.array = make([]LValue, 0, defaultArrayCap)
			}
			index := int(v) - 1
			alen := len(tb.array)
			switch {
			case index == alen:
				tb.array = append(tb.array, value)
			case index > alen:
				for i := 0; i < (index - alen); i++ {
					tb.array = append(tb.array, LNil)
				}
				tb.array = append(tb.array, value)
			case index < alen:
				tb.array[index] = value
			}
			return
		}
	case LString:
		tb.RawSetString(string(v), value)
		return
	}

	tb.RawSetH(key, value)
}
```
see 
```
			case index > alen:
				for i := 0; i < (index - alen); i++ {
					tb.array = append(tb.array, LNil)
				}
				tb.array = append(tb.array, value)
```

So when i define test[10000000] = {} in lua , gopher-lua will mapping a 10000000 lenght []LValue in go.
it waste too many memory.

Will you consider to use a map[int]LValue type  to mapping a lua array?

**Comment by yuin** [comment]
I dont.

GopherLua tables are acts like array when indicies are number. This is same behaviour as original Lua implementation.

You should `test["100000000"]` instead of `test[100000000]` because you need to an **associative array** rather than an **array** .

However, It may be better to decrease `MaxArrayIndex` in `config.go` .

**Comment by kevincoding525** [comment]
I try To fix this bug use your solution, but failed. it has memory leak
