### ISSUE TITLE
Unexpected string.gmatch result when trying to split paragraph in sentences.

### ISSUE THREAD

**Issue by fiatjaf** [yuin/gopher-lua#118]
Please answer the following before submitting your issue:

1. What version of GopherLua are you using? e57b64049898d04ad03d3cc75ffa770eb29aeae0
2. What version of Go are you using? go1.8
3. What operating system and processor architecture are you using? : linux/amd64
4. What did you do? : tried to run a `string.gmatch` call to iterate over sentences of a paragraph. code:

```go
package main

import lua "github.com/yuin/gopher-lua"

func main() {
        L := lua.NewState()
        defer L.Close()
        if err := L.DoString(`
local paragraph = 'the quick brown fox jumps over the lazy dog. while jumping, the quick brown fox realizes something.'
for sentence in string.gmatch(paragraph, "[^.!:]+") do
  print('sentence:', sentence)
end
    `); err != nil {
                panic(err)
        }
}
```

5. What did you expect to see? : each sentence printed independently. That's the behavior I see on `lua5.1` running on this same computer.
6. What did you see instead? : I see nothing. Nothing is printed, there's no error. nothing.

Other information:
* I also see the expected behavior if I run the same lua code on http://daurnimator.github.io/lua.vm.js/repl.html, but https://github.com/Shopify/go-lua gives me an error when running that, (`runtime error: [string ""]:3: attempt to call local '(for generator)' (a nil value`).
* Calling `print(anything)` either before or after the `gmatch` loop works ok, so it must mean that the `gmatch` is just returning nothing, there isn't a lua error happening.

**Comment by yuin** [comment]
I can not reproduce this issue.
It seems you use very old version of GopherLua. Please update your GopherLua dependency.

**Comment by fiatjaf** [comment]
Oh, updating GopherLua solved the problem. I'm sorry, I thought I was using a fairly recent version of GopherLua and didn't even think about updating it. Thank you!
