### ISSUE TITLE
Is it possible to preload modules written in Lua passed as strings?

### ISSUE THREAD

**Issue by fiatjaf** [yuin/gopher-lua#119]
Something like

```go
L := lua.NewState()
defer L.Close()
L.PreloadString("mymodule", `
local mymodule = {}

function mymodule.foo()
    print("Hello World!")
end

return mymodule
`)
L.DoString(`
local mymodule = require "mymodule"
mymodule.foo()
`)
```

I imagine it should be possible, but can't find the correct documentation for it.

**Comment by yuin** [comment]
Since GopherLua is a Lua implementation, the same thing as original Lua is not documented in GopherLua.

Please refer to [Lua 5.1 Reference manual](https://www.lua.org/manual/5.1/manual.html#pdf-require) and use `package.preload` .

**Comment by fiatjaf** [comment]
Sorry again, and thank you.

For future reference, here's what I ended up doing:

```go
L := lua.NewState()
defer L.Close()
mod, err := L.LoadString(`
local mymodule = {}

function mymodule.foo()
    print("Hello World!")
end

return mymodule
`)
preload := L.GetField(L.GetField(L.Get(lua.EnvironIndex), "package"), "preload")
L.SetField(preload, "mymodule", mod)
```

then

```go
L.DoString(`
local mymodule = require "mymodule"
mymodule.foo()
`)
```

**Comment by mofirouz** [comment]
Thank you so so so much for this - saved hours on end trying to figure this out

**Comment by tooolbox** [comment]
This should probably be in the README.
