### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by xyproto** [yuin/gopher-lua#12]
Thanks for writing gopher-lua, I'm using in it [algernon](https://github.com/xyproto/algernon) and it works great!

Best regards,
    Alexander F Rødseth

**Comment by yuin** [comment]
Thank you for informing me.

I was noticing from the [algernon](https://github.com/xyproto/algernon) source codes that an LState object is created for each http requests. To reduce LState creation costs, it may be better to use [The LState pool pattern](https://github.com/yuin/gopher-lua#the-lstate-pool-pattern), I think.

**Comment by xyproto** [comment]
Thanks! I implemented the suggested changes and everything works perfectly fine. It's hard to tell how much the performance improvement is (I'm sure it is there!), but it feels good to do it the proper way.
