### ISSUE TITLE
unsafeFastStringToReadOnlyBytes has unexpected behavior on GopherJS

### ISSUE THREAD

**Issue by fiatjaf** [yuin/gopher-lua#120]
- [x] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [x] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : b402f3114ec730d8bddb074a6c137309f561aa78
2. What version of Go are you using? : go1.8
3. What operating system and processor architecture are you using? : linux/amd64
4. What did you do? : tried to compile run the following code in [GopherJS](https://github.com/gopherjs/gopherjs) (`gopherjs run`):

```go
package main

import lua "github.com/yuin/gopher-lua"

func main() {
        L := lua.NewState()
        defer L.Close()
        if err := L.DoString(`
print(string.gsub("banana", "a", "A", 2))
    `); err != nil {
                panic(err)
        }
}
```
 
5. What did you expect to see? : `bAnAna  2`
6. What did you see instead? : `banana 0`

More information at the issue I created for this same problem at the GopherJS repo: https://github.com/gopherjs/gopherjs/issues/642

**Comment by waschik** [comment]
Seems to be fixed. Current output:
```
bAnAna	2
```

**Comment by fiatjaf** [comment]
Awesome!
