### ISSUE TITLE
Best way of converting LTable to JSON / Map

### ISSUE THREAD

**Issue by mofirouz** [yuin/gopher-lua#122]
Thanks for the awesome library.

We are using GopherLua in [Nakama](https://github.com/heroiclabs/nakama) to allow for custom sandboxed scripts to run within the server. The scripts will return a LTable object that is the result of the script return. We need to translate this LTable to a Map or JSON structure (they are in Lua), and send it down the wire.

What is the best way to achieve this behaviour?

**Comment by yuin** [comment]
https://godoc.org/github.com/yuin/gluamapper

**Comment by mofirouz** [comment]
Awesome thank you
