### ISSUE TITLE
Implementing dot properties for known items

### ISSUE THREAD

**Issue by thrisp** [yuin/gopher-lua#123]
How do I implement simple 

table.property 

get or set 

The front page shows 

table:function()

but trying interpolate from C Lua is confounding somewhat by the lack of lightuserdata

I'm hoping you can just point me to an example somewhere.

**Comment by yuin** [comment]
https://github.com/layeh/gopher-luar

**Comment by thrisp** [comment]
That helps a bit, but I've been looking at it and its not really a simple thing so I've just gone ahead and started doing it with what I know.
