### ISSUE TITLE
LNumber precision and formatting 

### ISSUE THREAD

**Issue by thrisp** [yuin/gopher-lua#124]
Can I get better precision getting numbers in and out or do I have a bug?

rough code snippets

go 
```
func Vec4(x, y, z, w float32) *vec4 {
	return &vec4{
		mgl32.NewVecNFromData([]float32{x, y, z, w}),
	}
}

// creates 
func lVec4(L *l.LState) int {
	x, y, z, w := float32(L.CheckNumber(1)),
		float32(L.CheckNumber(2)),
		float32(L.CheckNumber(3)),
		float32(L.CheckNumber(4))
	v := Vec4(x, y, z, w)
	ud := L.NewUserData()
	ud.Value = v
	L.SetMetatable(ud, L.GetTypeMetatable(VEC4))
	L.Push(ud)
	return 1
}

// unpacks on access
func vec4Index(L *l.LState) int {
	ud := L.CheckUserData(1)
	if v, ok := ud.Value.(*vec4); ok {
		req := L.Get(2)
		switch req.String() {
		case "x", "r", "s":
			L.Push(l.LNumber(v.Get(0)))
			return 1
		case "y", "g", "t":
			L.Push(l.LNumber(v.Get(1)))
			return 1
		case "z", "b", "p":
			L.Push(l.LNumber(v.Get(2)))
			return 1
		case "w", "a", "q":
			L.Push(l.LNumber(v.Get(3)))
			return 1
		}
	}
	L.RaiseError("vec4 expected")
	return 0
}
```
lua
```
cc=vec4(44.3,0.9,0.9,0.9)
print(cc.r, cc.g, cc.b, cc.a)
```

the output is: 

44.29999923706055	0.8999999761581421	0.8999999761581421	0.8999999761581421

where I expect:

44.3 0.9 0.9 0.9

can I get more control over this? I'm packing and unpacking float32, maybe this isnt the best way.

I probably need to apply formatting of some sort:

https://godoc.org/github.com/yuin/gopher-lua#LNumber.Format

**Comment by yuin** [comment]
This is not a matter of GopherLua but of Golang itself.

- https://play.golang.org/p/yHec03892-
- [go-nuts :float64(float32(0.6)) changes precision?](https://groups.google.com/forum/#!msg/golang-nuts/Xo-U56AA5Ug/uzCta25ldCkJ)

**Comment by thrisp** [comment]
Yes I realized that I need to handle the formatting going through and out.
