### ISSUE TITLE
Opcode in the first 6 bits of an instruction

### ISSUE THREAD

**Issue by ganehag** [yuin/gopher-lua#126]
I had started work on writing a Lua 5.1 semi-compatible* string.dump function for Gopher-Lua when I ran into problems. 

It appears to be that the instructions in Gopher-Lua are handled mirrored to the definition in "lopcodes.h" from the Lua 5.1 source code.

> All instructions have an opcode in the first 6 bits.
>   Instructions can have the following fields:
>         'A' : 8 bits
>         'B' : 9 bits
>         'C' : 9 bits
>         'Bx' : 18 bits ('B' and 'C' together)
>         'sBx' : signed Bx

Thus: _inst & 0x3F_ is used to extract the instruction.

But it Gopher-Lua the code to extract the opcode from the instruction is to shift it down 26 bits...

> return int(inst >> 26)

Is this intentional or just "the way it ended up"?

*Semi-compatible or more specifically not compatible at all, since Gopher-Lua uses a different set of opcodes than Lua 5.1.

**Comment by yuin** [comment]
This is intentional and "the way it ended up" .

GopherLua uses bytecodes as a just ”Intermediate representation", so is not interested in actual values.

I started the project in a way that is easy for me, and since I did not need to change it, I will come to now.

**Comment by ganehag** [comment]
It was so similar and yet so different from the Lua source implementation, that's why I asked. Either way works, especially since a compiled dump from GopherLua can't be compatible with Lua anyway.
