### ISSUE TITLE
Speed Up

### ISSUE THREAD

**Issue by linkerlin** [yuin/gopher-lua#135]
type callFrame struct {
	Idx        int
	Fn         *LFunction
	Parent     *callFrame
	Pc         int
	Base       int
	LocalBase  int
	ReturnBase int
	NArgs      int
	NRet       int
	TailCall   int
}

In x86_64, int is the same as int64, is too big for Pc,Base,LocalBase...
Replace int with int32 will make callFrame smaller and get a better performance.
Length of a L2 Cache line is 32-bytes .
Keep a callFrame in one cache-line is much faster.
And callFrame is the most important struct in the lua-vm.

**Comment by rucuriousyet** [comment]
Wanna submit a PR?
