### ISSUE TITLE
Strange nil error on lua thread

### ISSUE THREAD

**Issue by Raggaer** [yuin/gopher-lua#138]
- [x] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [x] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : 

Latest commit at this date; 2243d714d6c94951d8ccca8c851836ff47d401c9

2. What version of Go are you using? : 

Go 1.9

3. What operating system and processor architecture are you using? :

Windows/amd64

4. What did you do? :

I have the following Go code to execute background jobs

```go
// BackgroundEvent executes a background event
func BackgroundEvent(L *lua.LState) int {
	// Get function
	f := L.ToFunction(2)

	// Create new thread
	thread, _ := L.NewThread()

	// Close thread
	defer thread.Close()

	// Infinite loop
	go func() {

		for {

			// Resume function using  a new state thread
			status, err, _ := L.Resume(thread, f)

			// Check if event finished execution
			if status == lua.ResumeOK {
				break
			}

			if err != nil {

				L.RaiseError("Running event returned an error: %v", err)
				break
			}
		}
	}()

	return 0
}
```

With this lua code

```lua
events:new(
   function()
       local i = 0
       while true do
           print(tostring(i))
           if i >= 2 then
               return
           end
           i = i + 1
           sleep("1s")
       end
   end
)
```
The sleep function is also custom, it just calls `time.Sleep` parsing the duration string

5. What did you expect to see? :

No error

6. What did you see instead? :

The thread returns an error, when I inspect the error the message is just `nil` so I am not sure where this error is coming from.

**Comment by yuin** [comment]
I am soooo busy with work now, so put points I noticed briefly, you can do this kind of multithreading.

Lua threads( `L.NewThread()` ) **is not for a real thread, just for coroutines.**  You can not pass an `LState` object created by `L.NewThread()` to other goroutines. 

This behaviour is same as original Lua implementation.
