### ISSUE TITLE
can GopherLua support %f of regex?

### ISSUE THREAD

**Issue by Greyh4t** [yuin/gopher-lua#139]
- [ ] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [ ] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : 
the last version
2. What version of Go are you using? : 
1.9
3. What operating system and processor architecture are you using? :
4. What did you do?: 
5. What did you expect to see? :
6. What did you see instead? :

I found that GopherLua doesn't support %f of regex, which support in lua 5.1 but undocumented, is there any plane to add it?
Lua_reference_manual
https://www.mediawiki.org/wiki/Extension:Scribunto/Lua_reference_manual/zh

**Comment by yuin** [comment]
Currently it is not planned to implement this hidden feature. (Partly because I have been sooo busy with my work...)

**Comment by Greyh4t** [comment]
Thanks for your replay, i will try other method.
