### ISSUE TITLE
New library for GopherLua: gluasocket

### ISSUE THREAD

**Issue by drauschenbach** [yuin/gopher-lua#141]
A port of [LuaSocket](https://github.com/diegonehab/luasocket) is now available to GopherLua users. LuaSocket is the 6th post popular LuaRocks download, and provides capabilities for networking, system time, MIME parsing, and HTTP/SMTP/FTP. It is a very popular dependency in other modules, and so this opens the door to running many more LuaRocks modules in GopherLua.

We'd love a mention in your README alongside other [Libraries for GopherLua](https://github.com/yuin/gopher-lua#libraries-for-gopherlua), so that we can shake it down and build out what's missing.

https://github.com/BixData/gluasocket

**Comment by yuin** [comment]
Thanks for you contributions for the project.

I've added `gluasocket` library to the `Libraries for GopherLua` section in the README.
