### ISSUE TITLE
how to speed up using code cache

### ISSUE THREAD

**Issue by yyscamper** [yuin/gopher-lua#147]
Since usually I need to call a piece of lua code in my golang project for huge number of times. The lua code is always same, but with different parameters, below is the example:
```golang
L := lua.NewState()

param := L.NewTable()
param.RawSetString("foo", 10)

L.SetGlobal("param", param)
L.DoString(`
    param["foo"] = param["foo"] + 10
    ...
`)

result := L.GetGlobal("param")
....
```
For example, I need to set the `param["foo"]` from 1 to 1000000, and store all result.

I had some ideas to speed up:
(1) Compile the source code (or Parse the AST) only once at beginning, and it returns a intermediate value, then lua can directly run the value, so I can save the time for compilation or parsing.
(2) Cache the code string in lua state inside, then lua save time to parse and compile the source code if the code is already in cache.

I have no idea whether the lua has already implemented above features, if not, could you please tell me how to do it?

Thanks.

**Comment by yuin** [comment]
You can reuse a function.

Do this once

```lua
L := lua.NewState()
L.DoString(`
    function my_function(param)
      local result = {}
      result["foo"] = param["foo"] + 10
      return result
    end
    ...
`)
```

and you can run the code as many times as you want repeatedly

```lua
param := L.NewTable()
param.RawSetString("foo", 10)
if err := L.CallByParam(lua.P{
    Fn: L.GetGlobal("my_function"),
    NRet: 1,
    Protect: true,
    }, param); err != nil {
    panic(err)
}
ret := L.Get(-1) // returned value
L.Pop(1)  // remove received value


```
