### ISSUE TITLE
New library for GopherLua: gluabit32

### ISSUE THREAD

**Issue by drauschenbach** [yuin/gopher-lua#149]
A port of [bit32](https://luarocks.org/modules/siffiejoe/bit32) is now available to GopherLua users.

We'd love a mention in your README alongside other Libraries for GopherLua, so that we can shake it down and build out what's missing.

https://github.com/BixData/gluabit32

**Comment by yuin** [comment]
Thanks for your contributions for the project!

I've added gluabit32 library to the Libraries for GopherLua section in the README.
