### ISSUE TITLE
`L.ToInt` returns a bigger number with large integers

### ISSUE THREAD

**Issue by tsileo** [yuin/gopher-lua#152]
Hi there,

1. What version of GopherLua are you using? :  `b641d31de2ca5bf2f50bc04ef7c54149a4aa8b1f `
2. What version of Go are you using? : `go version go1.9.2 linux/amd64`
3. What operating system and processor architecture are you using? : Ubuntu 17.10 / amd64
4. What did you do? : Trying to pass a large int as an argument via Lua to a function defined in Go
5. What did you expect to see? : `ToInt` should return the int passed as an argument
6. What did you see instead? : It returns a bigger number

Basically, `my_lua_func(1513407461112281552)` causes `L.ToInt(1)` to return `1513407461112281600`. And if you're curious, the value is a timestamp in nanoseconds (generated by `time.Now().UnixNano()`).

Here is the code to reproduce the issue:

```go
package main

 import (
     "fmt"

     "github.com/yuin/gopher-lua"
 )

 func IntTest(L *lua.LState) int {
     i := L.ToInt(1)
     fmt.Printf("ToInt i=%v\n", i)
     return 0
 }

 func main() {
     L := lua.NewState()
     defer L.Close()
     i := 1513407461112281552
     fmt.Printf("arg=%v\n", i)
     L.SetGlobal("int_test", L.NewFunction(IntTest))
     if err := L.DoString(fmt.Sprintf(`
     i = %v
     print(i)
     int_test(i)`, i)); err != nil {
         panic(err)
     }
 }
```

And the output on my system:

```
arg=1513407461112281552
1513407461112281600
ToInt i=1513407461112281600
```
Is the reason a loss of precision because the int cannot be stored in 52 bits (because of the number conversion)? If so, I think it should return an error or something? Do you think it's worth working on a workaround for supporting large integers transparently? I guess I will use string for timestamp in the meantime.

Let me know if you need more informations or if I did something wrong,
Thanks!

**Comment by chai2010** [comment]
it is not a bug.

Lua has not real int64 type, it use double (ieee754) for int.
The ieee754 double only has 52 bits for int.

you can try the same code in Go:

```go
package main

import (
	"fmt"
)

func main() {
	f := float64(1513407461112281552)
	fmt.Println(int64(f)) // out: 1513407461112281600
}
```

**Comment by yuin** [comment]
@tsileo As chai2010 said, this is not a bug. C-lua5.1 behaves as same as GopherLua.

```c
#include <stdio.h>
#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"

int intTest(lua_State *L) {
  lua_Integer i = lua_tointeger(L, 1);
  printf("ToInt i=%lld\n", (long long)i);
  return 0;
}

int main(int argc, char* argv){
    lua_State *L = luaL_newstate();
    luaL_openlibs(L);
    lua_register(L, "intTest", &intTest);
    printf("value i=%lld\n", 1513407461112281552L);
    luaL_dostring(L, "i = 1513407461112281552; intTest(i);");	
    return 0;
}
```

This code prints a result without any errors.

```
value i=1513407461112281552
ToInt i=1513407461112281600
```

Lua is designed for extending host programs, so it's number precision is limited by host program language. You can use libraries that supports large numbers like https://bitbucket.org/tedu/bigintlua/src/tip/bigint.lua

**Comment by tsileo** [comment]
Thanks for the explanation, and thanks for the pointer!

**Comment by rezam90** [comment]
thanks yuin. BTW how to handle this? sometime I need to use int64 type in my code.
