### ISSUE TITLE
Luajit?

### ISSUE THREAD

**Issue by rucuriousyet** [yuin/gopher-lua#153]
I understand the reason to have a pure go library, but why not use luajit and cgo? The performance would be much better than what this provides.

**Comment by yuin** [comment]
What I wantted is

- pure go. It does not hurt go characteristics(easy cross platform compiling, single executable binary...)
- easy to use.  Lua stack APIs are annoying especially in table operations. 

Moreover a go library with luajit has already exist(https://github.com/aarzilli/golua), so I don't need to create same library.
