### ISSUE TITLE
Experiments with Moonscript... would love any input you may have...

### ISSUE THREAD

**Issue by rucuriousyet** [yuin/gopher-lua#154]
So I have been building a plugin system using Gopher Lua and I want to support Moonscript. To simply the development cycle I have created a bundle containing all of the Moonscript deps (pure Lua). This bundle works great for LuaJIT and Lua but has an error (see below) for glua... not sure if this is a lua 5.3 vs 5.1 issue or something else... I would love any input you can offer up here. I would definitely be willing to turn this into a Gopher Lua module if someone is interested.

```shell
# plugin git:master ● [^._.^]ﾉ彡ミ
$ glua testers.lua 
@/usr/share/lua/5.3/lulpeg.lua:1577: bad argument #1 to load (function expected, got string)
stack traceback:
	[G]: in function 'load'
	@/usr/share/lua/5.3/lulpeg.lua:1577: in function 'printers'
	@/usr/share/lua/5.3/lulpeg.lua:2839: in function 'LuLPeg'
	@/usr/share/lua/5.3/lulpeg.lua:2848: in function <@/usr/share/lua/5.3/lulpeg.lua:2794>
	@/usr/share/lua/5.3/lulpeg.lua:22: in function <@/usr/share/lua/5.3/lulpeg.lua:15>
	(tailcall): ?
	[G]: in function 'require'
	./moon-bundle.lua:2970: in function <./moon-bundle.lua:0>
	[G]: in function 'require'
	testers.lua:1: in main chunk
	[G]: ?
```
[moon-bundle.zip](https://github.com/yuin/gopher-lua/files/1580814/moon-bundle.zip)

I've been running this like so: (swap luajit with any lua, all files needed are in moon-bundle.zip)
`luajit testers.lua | luajit`

**Comment by yuin** [comment]
With e37e1695a7de72e7d4c5559206a7fb3a6d5a5e88, moonscript compiler seems to work for me.
Can you confirm it's working?

**Comment by rucuriousyet** [comment]
Yep, I just updated to the newest version of Glua and it seems to be able to compile/run the moonscript bundle I created just fine! Thanks for updating the project, I really appreciate it!

**Comment by rucuriousyet** [comment]
@yuin on a side note, would you be opposed to setting up versioning for this project with gopkg.in? I am using it for some really important stuff and would love to be able to version lock/vendor

**Comment by yuin** [comment]
I'm not planning to do it. You can do vendoring with a tool like https://github.com/golang/dep without gopkg.in.
