### ISSUE TITLE
Incorrect _VERSION field

### ISSUE THREAD

**Issue by pygy** [yuin/gopher-lua#156]
- [x] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [x] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Hello,

regarding `_VERSION`, the [reference manual says](https://www.lua.org/manual/5.1/manual.html#pdf-_VERSION) that it is: 

> A global variable (not a function) that holds a string containing the current interpreter version. The current contents of this variable is `"Lua 5.1"`.

However, GopherLua puts its own version there instead (`"GopherLua 0.1"`) . This [breaks](https://github.com/pygy/LuLPeg/issues/13) the LuLPeg version detection code (and probably other libs as well).

It would be nice if you could change this. For example LuaJIT has  `_VERSION == "Lua 5.1"`, and has its own version info in `jit.version`. While `_%u` variables are officially reserved for the PUC team, using `_GOPHER_LUA_VERSION` is unlikely to result in collisions.

**Comment by rucuriousyet** [comment]
Honestly this would be as simple as assigning the global _VERSION to whatever lua version you are working with before running anything else. `state.SetGlobal("_VERSION", "Lua 5.1")`

**Comment by pygy** [comment]
Indeed, but gopher-lua is AFAICT intended to be a Lua 5.1 implementation, so having it builtin would prevent further surprises for users.

**Comment by rucuriousyet** [comment]
Agreed

-sent from my OnePlus X

**Comment by yuin** [comment]
I've changed the _VERSION variable value and added a _GOPHER_LUA_VERSION variable.

**Comment by pygy** [comment]
Excellent, thanks!
