### ISSUE TITLE
Compat request: have string.rep accept negative repeat counts.

### ISSUE THREAD

**Issue by pygy** [yuin/gopher-lua#157]
- [x] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [x] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Using GopherLua 0.1

`string.rep("foo", -1)` returns the empty string in both Lua 5.1 and LuaJIT, but errors out in gopher-lua: `panic: strings: negative Repeat count`.

`string.rep(s, n)` is [said](https://www.lua.org/manual/5.1/manual.html#pdf-string.rep) to 

> Returns a string that is the concatenation of `n` copies of the string `s`. 

so negative counts probably fall into the realm of undefined behavior and erroring out is not per se out of spec, but it would be nice if it was compatible. I can send a PR if you want.

**Comment by yuin** [comment]
Now string.rep with regative repeat count returns an empty string.

**Comment by pygy** [comment]
Beautiful, thanks!
