### ISSUE TITLE
How to convert a go map to lua table？

### ISSUE THREAD

**Issue by dongyang03** [yuin/gopher-lua#160]

**Comment by chai2010** [comment]
map -> json -> table

**Comment by dongyang03** [comment]
@chai2010 ,在lua中序列化json没有golang快，能不能在golang中直接传递map或者struct，在lua里接受talbe？

**Comment by chai2010** [comment]
当然可以，不过需要自己遍历map或struct，然后填充table。

**Comment by bontibon** [comment]
Depending on your use case, you may find [gopher-luar](https://godoc.org/layeh.com/gopher-luar#New) does what you are looking for.

**Comment by zeroxer** [comment]
Any example to use MapToTable? @Raggaer
