### ISSUE TITLE
Addition of gmoonscript to readme

### ISSUE THREAD

**Issue by rucuriousyet** [yuin/gopher-lua#164]
Hi, I created a little [module](https://github.com/rucuriousyet/gmoonscript) that makes it rather simple to compile [Moonscript](https://moonscript.org) from Go or Gopher-Lua. It's rather rough since I am trying to call an embedded amalgamation of the Lua-based Moonscript library, I would love to get some input on possbile improvements before I submit a PR to add this library to the list in the Readme. 

Right now the module does some weird importing of the Moonscript bundle I've created and wraps the parse & compile methods with `compile(code)` method. Error handling is my primary concern, but I also would love to remove all the globals used by this module that shouldn't be accessible to the importer.

**Comment by yuin** [comment]
@rucuriousyet Looks it doesn't matter. You can use libraries like jessevdk/go-assets instead of implementing binary data management by yourself.

**Comment by yuin** [comment]
I'd just been thinking of bumping Go version up, I'll take care of that.

**Comment by rucuriousyet** [comment]
Okay, great thanks. Please let me know if you think there are any
improvements to be made.

-sent from my OnePlus X
