### ISSUE TITLE
DoFile with empty string

### ISSUE THREAD

**Issue by quirinux** [yuin/gopher-lua#173]
gopher-lua gets stuck if DoFile is called with a empty string, it's easy to reproduce like

lua.DoFile("")

**Comment by bontibon** [comment]
This is correct behaviour.

[loadfile](https://www.lua.org/manual/5.1/manual.html#pdf-loadfile):
> Similar to load, but gets the chunk from file filename or from the standard input, if no file name is given.

[luaL_loadfile](https://www.lua.org/manual/5.1/manual.html#luaL_loadfile):
> If filename is NULL, then it loads from the standard input.
