### ISSUE TITLE
int64 last digit changes (treated as float64)

### ISSUE THREAD

**Issue by rezam90** [yuin/gopher-lua#174]
Hi

1. I'm using the ? : GopherLua 0.1
2. What version of Go are you using? : 1.9.3
3. What operating system and processor architecture are you using? : macOS 10.13.1
4. What did you do? : convert lua `LNumber` to `int64`
5. What did you expect to see? : `342161316540874753` 
6. What did you see instead? : `342161316540874752`

I think it's treated as `float64`.
How can I convert my `int64` without being changed or converted to `float64`.
Does goher-lua has another type than 'LNumber'? as its type is `float64`

**Comment by yuin** [comment]
This is same behavior as original Lua. LNumber is always `float64` . See #152
