### ISSUE TITLE
Metatable __newindex doesn't trigger anymore after table.RawSet(key, value)

### ISSUE THREAD

**Issue by FabianTerhorst** [yuin/gopher-lua#176]
Im currently using the metatable __index and __newindex to verify table assigns and access. The problem is that only the first assign triggers the function, every assign that happens after table.RawSet(key, value) doesn't trigger the meta table anymore, Is there a way to assign an value to the table inside the metatable callback without causing an stackoverflow when using L.SetTable(table, key, value) or none callbacks when using table.RawSet(key, value)?
```golang
globalEnvMetaTable := L.NewTypeMetatable("GlobalMetaTable*")
globalEnvMetaTable = L.SetFuncs(globalEnvMetaTable, map[string]lua.LGFunction{
	"__newindex": assign,
	"__index":    access,
})
L.G.Global.Metatable = globalEnvMetaTable
...

func assign(L *lua.LState) int {
	table := L.CheckTable(1)
	key := L.CheckAny(2)
	value := L.CheckAny(3)
	table.RawSet(key, value)
	return 0
}

func access(L *lua.LState) int {
	table := L.CheckTable(1)
	key := L.CheckAny(2)
	L.Push(table.RawGet(key))
	return 1
}
....
L.SetGlobal("....", lua.LNumber(....))
```

**Comment by zetamatta** [comment]
I recommend you attach the source file to confirm the problem with `go run`.

[issue176-2.go.txt](https://github.com/yuin/gopher-lua/files/2015628/issue176-2.go.txt) ( Please rename *.go.txt -> *.go )

Run `go run issue176-2.go`, and we expect:

```
access called
nil
assign called
access called
1
```

But

```
access called
nil
assign called
1
```

**Comment by zetamatta** [comment]
I made #177 to fix #176. If there are no prolblems, would you merge ?

```
$ go run issue176-2.go
access called
nil
assign called
access called
1
```

**Comment by zetamatta** [comment]
Sorry, I found it is compatbile with Lua.org's Lua .

```foo.lua
m = {
    __index=function(tbl,key)
        print("access!")
        return rawget(tbl,key)
    end ,
    __newindex=function(tbl,key,val)
        print("assign")
        rawset(tbl,key,val)
    end,
}

foo = setmetatable({},m)
print(foo[1])
foo[1] = 1
print(foo[1])
```

lua.org's Lua: (lua 5.3)

```
$ lua foo.lua
access!
nil
assign
1
```

GopherLua's glua.exe:

```
$ ~\go\src\github.com\yuin\gopher-lua\cmd\glua\glua.exe foo.lua
access!
nil
assign
1
```

**Comment by yuin** [comment]
@FabianTerhorst @zetamatta As zetamatta says, This is a not bug but a specification of Lua.

Lua reference manual section [2.8 – Metatables ](https://www.lua.org/manual/5.1/manual.html#2.8) describes 

> __newindex : The indexing assignment table[key] = value.

```lua
     function settable_event (table, key, value)
       local h
       if type(table) == "table" then
         local v = rawget(table, key)
         if v ~= nil then rawset(table, key, value); return end
         h = metatable(table).__newindex
         if h == nil then rawset(table, key, value); return end
       else
         h = metatable(table).__newindex
         if h == nil then
           error(···)
         end
       end
       if type(h) == "function" then
         h(table, key,value)           -- call the handler
       else h[key] = value             -- or repeat operation on it
       end
     end
```

`__newindex` is not called If `rawget(table, key)` returns a value.

So, @FabianTerhorst your question is not about GopherLua but about Lua itself.

**Comment by FabianTerhorst** [comment]
Thanks for clarification.
