### ISSUE TITLE
How to avoid an infinite loop from an arbitrary script?

### ISSUE THREAD

**Issue by ortuman** [yuin/gopher-lua#179]
- [x] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [x] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : 
Lua 5.1
2. What version of Go are you using? : 
1.10
3. What operating system and processor architecture are you using? :
OS X
4. What did you do? :
5. What did you expect to see? :
6. What did you see instead? :

**Comment by tul** [comment]
Hi - you can use context's to terminate a running `LState` if it has been running too long (eg in an infinite loop)

Example from the README

```
L := lua.NewState()
defer L.Close()
ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
defer cancel()
// set the context to our LState
L.SetContext(ctx)
err := L.DoString(`
  local clock = os.clock
  function sleep(n)  -- seconds
    local t0 = clock()
    while clock() - t0 <= n do end
  end
  sleep(3)
`)
// err.Error() contains "context deadline exceeded"
```
