### ISSUE TITLE
gometalinter fails on master branch of Go

### ISSUE THREAD

**Issue by nordinvannes** [yuin/gopher-lua#182]
- [X] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [X] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : 
last
2. What version of Go are you using? : 
master branch
3. What operating system and processor architecture are you using? :
Windows / Intel
4. What did you do? :
Run gometalinter
5. What did you expect to see? :
No error
6. What did you see instead? :
An error on loop detection on preloadLimit

**Comment by yuin** [comment]
This issue seems to be a bug in `go vet` . see https://github.com/golang/go/issues/26124

**Comment by yuin** [comment]
Now we have a Go1.11 release. This issue has been fixed in Go1.11 release.
