### ISSUE TITLE
How to do io.input( <*os.File instance created by os.Pipe() or os.Open() on my application> )

### ISSUE THREAD

**Issue by zetamatta** [yuin/gopher-lua#188]
- [x] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [x] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? :   latest(  46796da1b0b4794e1e341883a399f12cc7574b55 )
2. What version of Go are you using? : go version go1.10.3 windows/amd64
3. What operating system and processor architecture are you using? : Windows10/amd65
4. What did you do? : -
5. What did you expect to see? : -
6. What did you see instead? : -

I want to call `io.input( <*os.File instance created by os.Pipe() or os.Open() on my application> )`.
The userdata `"FILE*"` is the instance of the type `lua.lFile` defined on iolib.go.
I can not push `lua.lFile` to lua stack as userdata because it is the private class of GopherLua.

Is there any good way to do it?

**Comment by yuin** [comment]
@zetamatta 
There is no neat way for this as Original C-Lua do.

- You can re-implement `io.input` and override the function.
- You can fork GopherLua and make the `lFile` struct public.
    - Original C-Lua has no explicit public APIs for this, so I'm not willing to create a new APIs.

**Comment by zetamatta** [comment]
> There is no neat way for this as Original C-Lua do

I agree. When I used lua53.dll from golang, I pushed the userdata as filehandle like :

```
type stream_t struct {
	FilePtr ansicfile.FilePtr // = filehandle compatible with FILE* of stdio.h
	Closer  uintptr // = bool
}
```

This was the undocumented way. So I understand my issue is hard to solve.

> You can fork GopherLua and make the lFile struct public

Ok, I will try it and search the style that can be merged. Thank you.
