### ISSUE TITLE
How to share compiled byte code between LStates

### ISSUE THREAD

**Issue by tul** [yuin/gopher-lua#192]
Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : 46796da1b0b4794e1e341883a399f12cc7574b55
2. What version of Go are you using? : 1.10.3 
3. What operating system and processor architecture are you using? : darwin/amd64
4. What did you do? : Try to share byte code between LStates
5. What did you expect to see? : Documentation
6. What did you see instead? : None

If I want to run a lua file in a LState, gopher lua offers `DoFile`, but `DoFile` will compile a fresh copy of the lua script for every LState. This will use memory unnecessarily when the same script has already been compiled and is already in memory elsewhere.

PR #193

**Comment by Raggaer** [comment]
I am really interested on this issue/PR, what has to be done so it gets merged?

**Comment by yuin** [comment]
@tul @Raggaer Sorry for late response, I've just merge the PR.

**Comment by t57root** [comment]
@yuin 
Is there some way that I can extract compiled byte code into a byte array, which then can be loaded directly by the VM? This would be useful for lua code protection. Thanks!
