### ISSUE TITLE
Memory optimisations for discussion

### ISSUE THREAD

**Issue by tul** [yuin/gopher-lua#197]
In my use case, I host a large number (10,000+) of LStates within one go process. In order to achieve this in reasonable memory, I have profiled and done a number of memory optimisations to gopher lua for my use case, some of which may be of wider interest. I would have to spend a bit of time to split my local changes into nice and separate pull requests, but before I do that, are the following of interest:

1. Read only lua table extension
Lua doesn't support a way to make a table read only. The most you can do is stop creation of new values via a `__newindex` callback, but you can't stop modification of already existing values. This extension allows a gopher Lua LTable to be marked a read-only, which will then raise a Lua error if a script tried to modify it.

This then allows for huge memory savings, as all the type meta tables and base libraries to be shared across all LStates safe in the knowledge that they cannot be modified. In my use case this saved 1GiB of memory.

However, it is a non Lua standard extension and introduces a difference between what gopher lua can do compared to the Lua 5.1 spec. However, the calling lua scripts are not changed, so the scripts remain portable.

2. Auto growing call stack
Rather than having a fixed size call stack per LState, allocate it in pages from a shared Go `pool`. This incurs a slight overhead to stack operations, but allows for the same application to host a variety of lua scripts without having to size the LStates according to each script up front.

3. Auto growing registry
Similarly to the auto growing call stack, but for the registry.

2 and 3 together saved around 700MiB for my use case.

I also investigated making the call stack smaller by changing various values in the `callFrame` structure to be `uint32` and `uint16` instead of `int`, but it messed the code up a lot and much better savings were achieved through the auto growing call stacks, so I abandoned this.

Please let me know if any of these changes are of interest and I can tidy them up and make nice pull requests for consideration.

**Comment by yuin** [comment]
@tul , I'm really grateful for your efforts . My opnion on your proposals are:

Imutable objects are commonly used in many languages for optimizations, But as you have pointed out, this is not included in Lua standard specs. Maybe next time.

Auto growing call stack and auto growing registry, I would like to adopt this features. But fixed size stack and fixed size registry have some advantages:

- protecting your systems from unlimited memory comsumption by untrasted third party scripts 
- performance: heap allocations are slow operation in golang

So, this features should be an optional for GopherLua users,

1. change `callFrameStack` and `registry` from structs to interfaces
    - these interfaces have 2 implementations: fixed and auto growing
2. add new options to `Options`. i.e : `AutoGrowingStack` and `AutoGrowingRegistry`

some thing like this.

 I am looking forward to your pull request  :blush:

**Comment by tul** [comment]
@yuin thanks for your feedback, that all seems reasonable. I will make the appropriate changes over the next week or two and prepare the PRs for your review.

**Comment by rhettli** [comment]
@tul  Can you provide function   L.Sate.clearLuaMemory() or L.Release() to let lua state instate to be resue in another task?without this method ,it will spend too much memory

Just two lua state instance spend me 400MB memory.

**Comment by tul** [comment]
@rhettli is this for when you have finished with an LState and wish to reclaim its memory? If so, calling LState.Close() and clearing all references to the LState so it can be GC-ed will reclaim.

Please share any more info you have on your problem.

**Comment by tul** [comment]
Ah I see there is more info on your question in #249 , let’s continue the discussion there.
