### ISSUE TITLE
How to validate Lua syntax?

### ISSUE THREAD

**Issue by drauschenbach** [yuin/gopher-lua#198]
Is there an API call to validate Lua syntax?

I've used the `parser.Parse(reader, name)` fn directly and can't get it to complain using junk content.

I've also used `L.LoadString(string)` and can't get it to complain about junk content.

**Comment by yuin** [comment]
`parse.Parse` can be used for validating lua syntax.

```go
package main

import (
	"github.com/yuin/gopher-lua/parse"
	"strings"
)

func main() {
	reader := strings.NewReader(
		`local a = 1 + 1
		 local b = 1 -
	     local c = "hogehoge"
	`)
	_, err := parse.Parse(reader, "<string>")
	if err != nil {
		println(err.Error())
	}
}
```
output:

```
<string> line:3(column:11) near 'local':   syntax error
```

**Comment by yuin** [comment]
Due to lack of your response I am closing this issue for now. Please feel free to reopen this issue if you have any questions.

**Comment by drauschenbach** [comment]
This works great -- thanks!
