### ISSUE TITLE
Best way to set LUA_PATH?

### ISSUE THREAD

**Issue by kabukky** [yuin/gopher-lua#20]
Hi,
I love working with gopher-lua so far. The documentation is lacking tough.
What would be the best way to set the LUA_PATH? In order to load modules from subdirectories located relative to the executed .lua file, I need to set it to the directory of that .lua file.
I discovered that the Lua vm uses system env variables set via os.Setenv(). Is there a way to set / append to the LUA_PATH just for one vm (e.g. vm.Setenv())?

Thanks

**Comment by yuin** [comment]
Hi.

Thanks for working with GopherLua.
You can do it in much the same way as the original Lua implementation.
[package.path](http://www.lua.org/manual/5.1/manual.html#pdf-package.path)  is the path used by ``require`` to search for a GopherLua loader. 

 The best way that you might want is to set ``package.path`` as follows:

    local script_path = _getscriptdir() -- implement in your host golang program
    package.path = script_path .. [[/subdir/?.lua;]] .. package.path

**Comment by kabukky** [comment]
That seems sensible, thank you :)
But I'm getting this error when executing test.lua:
```
[G]: plugins line:1(column:1) near '':   Invalid token

stack traceback:
	[G]: in anonymous function
	[G]: in require
	test.lua:2: in main chunk
	[G]: ?
```
Here's what my `lua.test` looks like (getCurrentDir() returns ";/absolute/path/to/script/dir"):
```
package.path = package.path .. getCurrentDir()
require "testmod"
print(testmod.foo())
```
Here's what my `testmod.lua` looks like:
```
local testmod = {}

function testmod()
    return "Hello World!"
end

return testmod
```

I'm new to Lua, so please excuse me if this is obvious. But from what I gather from the reference, this should load the module, right?

Thanks

**Comment by yuin** [comment]
package.path = package.path .. getCurrentDir()

to

    package.path = package.path .. getCurrentDir() .. [[/?.lua]]

Refer to [Lua5.1 - package.loaders section](http://www.lua.org/manual/5.1/manual.html#pdf-package.loaders) for further information.

**Comment by kabukky** [comment]
Thank you so much, I forgot about the .lua wildcard.
 I'm using GopherLua to drive the plugin system of [Journey](https://github.com/kabukky/journey) now :)
