### ISSUE TITLE
go1.11 introduces a regression around lua execution.

### ISSUE THREAD

**Issue by swsnider** [yuin/gopher-lua#202]
- [x] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [x] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : HEAD (f6fcaab0c612d877d4140cbdf6966aed51e6eebd)
2. What version of Go are you using? : 1.11
3. What operating system and processor architecture are you using? : darwin/amd64
4. What did you do? : I ran the below program
5. What did you expect to see? : the string "correct" on stdout
6. What did you see instead? : the string "failure"

**NOTE**: I get the string "correct" under go1.10 with no other changes (same gopherlua version and code).

```go
package main

import (
        "fmt"
        "os"

        "github.com/yuin/gopher-lua"
)

const lua_src = `
t = {}
ok, res = pcall(table.remove, t)
if not ok or not res then
    table.insert(t, {})
else
    print("failed to work")
end
ok, res = pcall(table.remove, t)
ok, res = pcall(table.remove, t)
if not ok or not res then
    print("correct")
else
    print("failure")
end
`

func main() {
        L := lua.NewState()
        defer L.Close()

        if err := L.DoString(lua_src); err != nil {
                fmt.Fprintf(os.Stderr, "failed to execute lua", "error", err)
        }
}
```

**Comment by yuin** [comment]
@swsnider I've just fixed the issue in the latest commit. Can you confirm that the bug is fixed?

**Comment by swsnider** [comment]
Works great! Thanks!
