### ISSUE TITLE
pcall Throws Error on nil

### ISSUE THREAD

**Issue by guysv** [yuin/gopher-lua#204]
- [x] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [x] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? :
```bash
$ go/bin/glua -v
GopherLua 0.1 Copyright (C) 2015 -2017 Yusuke Inuzuka
```

2. What version of Go are you using? : 
```bash
$ go version
go version go1.11.1 linux/amd64
```
3. What operating system and processor architecture are you using? :  ^^^
4. What did you do? : pcall(nil)
5. What did you expect to see? : 
```lua
#!lua5.1
print(pcall(nil))
false	attempt to call a nil value
```
6. What did you see instead? :
```lua
#!glua
print(pcall(nil))
<string>:1: bad argument #1 to pcall (function expected, got nil)
stack traceback:
	[G]: in function 'pcall'
	<string>:1: in main chunk
	[G]: ?
```

Just a tiny inconsistency with lua5.1 that hurts code portability

**Comment by yuin** [comment]
@guysv I've fixed this issue in the latest commit.
