### ISSUE TITLE
Add support for Go modules

### ISSUE THREAD

**Issue by maxekman** [yuin/gopher-lua#205]
Would be great to have go.mod and go.sum files added, together with tagged releases following the Go 1.11 modules convention: https://github.com/golang/go/wiki/Modules

**Comment by glatteis** [comment]
This seems like something that has been done now. This issue could be closed.

**Comment by AlekSi** [comment]
There is no go.mod in the master branch. See also https://github.com/yuin/gopher-lua/issues/208.

**Comment by wvell** [comment]
This would really help
