### ISSUE TITLE
Why gopher-lua run need so much memery?

### ISSUE THREAD

**Issue by zgame** [yuin/gopher-lua#206]
require a  lua file(670k) ,  app cost  70M memery,   I  create 10 goroutines , cost 700M memery.   why gopher-lua need so much memery

**Comment by zgame** [comment]
I change the code from  
table = {
[1003054] = {  ...}
} 
to 
table = {
["1003054"] = {  ...}
}

one LState need 10M memery ,  I  need  1000 LStates, so  all  LStates need 10G memery ,  too much .  how can I use little memery?

**Comment by yuin** [comment]
See #117.

>> one LState need 10M memery , I need 1000 LStates, so all LStates need 10G memery , too much . how can I use little memery?

It is strange. I suspect that your code contains a bad code like `table = {[1003053={...}}` .

**Comment by zgame** [comment]
thanks
