### ISSUE TITLE
Context Without Performance Penalty

### ISSUE THREAD

**Issue by jakevn** [yuin/gopher-lua#207]
1. What version of GopherLua are you using? : refs/heads/master a0dfe84f6227cda1c5f975bf3e35d55ae0d3df61
2. What version of Go are you using? : go1.11.1 darwin/amd64
3. What operating system and processor architecture are you using? : OSX 10.11.6 - i7 QC (MBP 2015)

Hello, I was playing around with ideas for preemption of goroutines for the use of aborting execution of interpreters without the performance overhead. I found that I was able to get performance within margin of error on my system by replacing `mainLoopWithContext` as so:

```
func mainLoopWithContext(L *LState, baseframe *callFrame) {
	var inst uint32
	var cf *callFrame
	if L.stack.IsEmpty() {
		return
	}

	L.currentFrame = L.stack.Last()
	if L.currentFrame.Fn.IsG {
		callGFunction(L, false)
		return
	}

	jumpTableRef := jumpTable

	defer func() {
		if r := recover(); r != nil {
			return
		}
	}()

	go func() {
		<-L.ctx.Done()
		jumpTableRef = [opCodeMax + 1]instFunc{}
	}()

	for {
		cf = L.currentFrame
		inst = cf.Fn.Proto.Code[cf.Pc]
		cf.Pc++
		if jumpTableRef[int(inst>>26)](L, inst, baseframe) == 1 {
			return
		}
	}
}
```

Thoughts?

**Comment by yuin** [comment]
Sorry for very late response.
Interesting.

Does `go build -race` claims any errors?

**Comment by yuin** [comment]
closed due to inactivity
