### ISSUE TITLE
Release possible?

### ISSUE THREAD

**Issue by Klaus-Tockloth** [yuin/gopher-lua#208]
Is it possible to build a release?

**Comment by yuin** [comment]
I am planning to release v1.0 after #197  is completed.
But It seems that #197 has being stopped. So I may release v1.0 at an early date.

**Comment by AlekSi** [comment]
Any tag, even `v0.1.0`, will be useful for dependency management.

**Comment by gudvinr** [comment]
@yuin friendly reminder that #197 was closed almost year ago
