### ISSUE TITLE
The gc problem

### ISSUE THREAD

**Issue by slrem** [yuin/gopher-lua#212]
Write in the lua script: 
local tbl = {}
Is memory allocated on the heap or the stack? 
Do many of these tables cause excessive gc pressure？

**Comment by yuin** [comment]
Table objects are allocated on the heap.

Table objects in lua are `LTable` struct defined in `value.go` and these objects are allocated by the `newLTable` function. Thus creating **too many** tables **MAY** cause gc problems.
