### ISSUE TITLE
If can add the function for debug by add a break point?

### ISSUE THREAD

**Issue by Think-Jumper** [yuin/gopher-lua#218]
If can add the function for debug by add a break point?
I mean that if can make the Lua Debugger or other Lua Editor can attach the execute file which build by gopher-lua to add some breakpoint for debug lua code？

**Comment by yuin** [comment]
You can't.

Lua has a `debug.sethook` function, but GopherLua does not implement this function(see [Differences between Lua and GopherLua](https://github.com/yuin/gopher-lua#differences-between-lua-and-gopherlua)).

**Comment by tul** [comment]
#131 may help
