### ISSUE TITLE
It seems not support the lua coroutine?

### ISSUE THREAD

**Issue by Think-Jumper** [yuin/gopher-lua#219]
It seems not support the lua coroutine? Could you please add functions to support the real lua coroutine? Make it better. ```!(~__~)!```

**Comment by yuin** [comment]
GopherLua supports fully coroutine functionalities.

**Comment by 4ov** [comment]
Hello @yuin , I'm very new to lua i hope you help me, i'm trying to make this code snippet of code work 
```lua
require "coroutine"

coroutine.wrap(function ()
    while true do
        print("lol")
        os.execute("sleep 1")
    end
end)()
print("Hello world")

```

i expect to see the `Hello world` message but it's never been reached (like i call normal function not a thread)
thanks in advance
