### ISSUE TITLE
Using tween library fails

### ISSUE THREAD

**Issue by Chillance** [yuin/gopher-lua#220]
Hi!

I like this project. The documention to get going is good and one big reason I decided to try this one.
Now, I wanted to try to use https://github.com/kikito/tween.lua with this but stumbled upon errors. I tested using Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio on Ubuntu 16.04.

So, I have this Go code:
```go
L := lua.NewState()
defer L.Close()
err := L.DoFile("luatest.lua")
if err != nil {
    panic(err)
}
```
And this simple luatest.lua file:
```lua
local tween = require('tween')

local label = { x=200, y=0, text = "hello" }
local labelTween = tween.new(4, label, {y=300}, 'outBounce')

local complete = labelTween:update(0.2)
print(label.y)
complete = labelTween:update(0.5)
print(label.y)
```

Using the lua binary in Ubuntu this seem to work fine. Running "lua luatest.lua" I get:
```
5.671875
69.48046875
```
printed. However, using Go, I get:
```
panic: ./tween.lua:271: Parameter 'y' is missing from subject or isn't a number
stack traceback:
        [G]: in function 'assert'
        ./tween.lua:271: in function 'checkSubjectAndTargetRecursively'
        ./tween.lua:286: in function 'checkNewParams'
        ./tween.lua:357: in function 'new'
        luatest.lua:15: in main chunk
        [G]: ?

goroutine 1 [running, locked to thread]:
main.testLUA()
```

So, what am I missing here? Some kind of Lua 5.1 functionality missing or?

Thanks!

**Comment by yuin** [comment]
This is a bug in the GopherLua compiler. 

Assignment statements that have multiple left asignees and right values with function calling like

```lua
local v = {}
local a,b
a, b = f(1), f(2)
```

produces a invalid byte codes. Thus a value stored in `0` register will be corrupted.

I've fixed this bug in 507fb6e. Could you confirm if this bug is fixed?
