### ISSUE TITLE
insert a big key value (100000000) into the table. 

### ISSUE THREAD

**Issue by qghappy1** [yuin/gopher-lua#221]
When the table creates 99999999 null keys, it wastes too much memory. 

func (tb *table) insert(key int, value interface{}) {
	if key>0 {
		if key>len(tb)+1 { 
		   tb.dict[key] = value
		}else if key == len(tb)+1 {
			tb.dict[key] = nil 
			tb.array = append(tb.array, value)
		}else{
			tb.array[key-1] = value 
		}
	}
}

**Comment by yuin** [comment]
see #117
