### ISSUE TITLE
Really bad performance for vector addition

### ISSUE THREAD

**Issue by guerillagrow** [yuin/gopher-lua#225]
Go version: 1.11.4 linux amd64
GopherLua version: master

I ran in to some strange performance issue when doing vector additions.
The Lua code runs fine and blazingly fast on the lua online demo site and with the regular clua intepreter too.

I have no idea  why GopherLua performs so bad. I mean really bad.
I use a default table as my vector with a "__add" metamethod, the vector contains only one element.
Here is my Lua code and my time measurements:

```
local _set = {
	__add = function(k, x)
		local sum = {}
		if #k >= #x then
			for i, v in ipairs(k) do
				sum[i] = v+(x[i] or 0)
			end
		else
			for i, v in ipairs(x) do
				sum[i] = v+(k[i] or 0)
			end		
		end
		return sum
	end;
}

local function set(t)
	local o = t or {}
	setmetatable(o, _set)	return o
end

local t = set({1})

print("Addition #1 (still acceptable performance 20 additions)...")
print("Result:",(t + t + t + t + t + t + t + t + t + t + t + t + t + t +t + t + t + t + t + t)[1])

print("Addition #2 (horrible performance 27 additions)")
print("Result:",(t + t + t + t + t + t + t + t + t + t + t + t + t + t + t + t + t + t + t + t + t +t + t + t + t + t + t)[1])

-- real	0m11.506s
-- user	0m14.460s
-- sys	0m0.385s
```

Has anyone an idea why GopherLua performs so bad?

Edit: Also tested it with Shopifys Lua intepreter and it performs normal so I guess there musst be a problem somwhere.

**Comment by guerillagrow** [comment]
I also found out that all "x+x+x+x+..." kind expressions like:
```
print(1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+11+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1)
real	0m11.649s
user	0m14.549s
sys	0m0.441s

```
take a long time to compute.
Is there any known issue related to that?

**Comment by guerillagrow** [comment]
What I found out so far is that it is the expression "table + table ..." that takes a long time to parse/prepare.
For example if I define an function which makes a huge vector addition but never runs in my code is also take a long time to compute. So it has to be some other problem than the code execution of the VM.

f.e. this code also performs bad:
```
os.exit() -- Exit before execution
local _set = {
	__add = function(k, x)
		local sum = {}
		if #k >= #x then
			for i, v in ipairs(k) do
				sum[i] = v+(x[i] or 0)
			end
		else
			for i, v in ipairs(x) do
				sum[i] = v+(k[i] or 0)
			end		
		end
		return sum
	end;
}

local function set(t)
	local o = t or {}
	setmetatable(o, _set)
	o.__newindex = function(self, k, v)
		print("newindex")
	end;
	return o
end

local t = set({1})

print("Addition #1 (still acceptable performance 20 additions)...")
print("Result:",(t + t + t + t + t + t + t + t + t + t + t + t + t + t +t + t + t + t + t + t)[1])

print("Addition #2 (horrible performance 27 additions)")
print("Result:",(t + t + t + t + t + t + t + t + t + t + t + t + t + t + t + t + t + t + t + t + t +t + t + t + t + t + t)[1])

```

**Comment by yuin** [comment]
@guerillagrow Thank you for your detailed report. Wrong compile time constant foldings have executed invalid recursive foldings. This causes an exponential performance degradation depending on number of binary operators( `+`, `-`, `%` ...)

I've fiexed the issue in c65cf42.
