### ISSUE TITLE
local variables's memory is not released by gc

### ISSUE THREAD

**Issue by SeniorPlayer** [yuin/gopher-lua#227]
lua code:

```lua
function Sleep(n)
   os.execute("sleep " .. n)
end
function Test()
    local a = {}
    for i=1, 10000 do
        local b = {}
        for j=1, 10000 do
            b[j] = j
        end
        a[i]= b
    end
    Sleep(5)
    print(#a)
end
Test()
Sleep(2)
collectgarbage("collect")
Sleep(1200)
print("sleep end")
```

compare memory usage of glua and lua5.1
glua test.lua
glua 0.0 00:21.51 12 0 21 4857M

glua's memory usage is always 4857M

lua5.1 test.lua
lua-5.1 0.0 00:03.53 1 0 10 2504M
lua-5.1 0.0 00:03.70 1 0 10 7408K

lua5.1's memory usage from 2504M down to 7408K

The local variables's memory should released by gc after the function return.

**Comment by yuin** [comment]
GopherLua uses Go's GC, thus GopherLua does not implement garbage collections.
So it may be hard to change this behaviour, I will give it a try to work this problem if I have time to spare.

**Comment by epikur-io** [comment]
I tested something similar and explicitly set a large table to nil and forced to free memory using golangs debug.FreeOSMemory() function, but no memory at all was released. This looks strange to me.
Here is the sample code I ran:

```lua
do
    local list = {}
    for i = 0,10000000,1 do -- allocates about 1.9 GB of memory
        local cls = {"EpiKkur", i}
        table.insert(list, cls)
    end
    list = nil
end
print("Next runGC: [Enter]")
io.read("*l")
gos.runGC() -- runs golangs runtime.GC()
print("Next free mem: [Enter]")
io.read("*l")
collectgarbage() 
gos.freeosmem() -- runs golangs debug.FreeOSMemory() at least here the memory should be freed since the local table was explicitly set to nil!
io.read("*l")
```

**Comment by guerillagrow** [comment]
I also recently ran into this issue. I use a pool of lua VMs that can execute functions that where previously registered. If a functions builds up a larger local table that memory is never ever returned. I consider this a bug. However I don't know if this is because of a bug in gopher lua or simply the golang GC.

I'm not really familiar with gopher lua's code base neither do I know how Go's GC works internally.
I think since gopher lua's local stack is a map/slice and Go's slices/maps are basically pointers so the memory location might only be freed if pointer changes (new pointer value / new map/slice).

**Comment by epikur-io** [comment]
I investigated a bit and looked at the source And found following note about memory allocators LNumber2I method:

> // The downside of this is that all of the floats on a given block have to become eligible for gc before the block
> // as a whole can be gc-ed.  

What does that exactly mean?
Can a large table be split across multiple "memory blocks" and thus cause not to be freed correctly?

**Comment by guerillagrow** [comment]
Looked at the code and it seems that LState's memory can only grow, as I understood.  So Go's GC can only free the memory if the LState can be garbage collected, so basically when you discard / respawn your VM.
Maybe a resizable memory allocator that removes empty memory blocks would fix the problem.

**Comment by tul** [comment]
I've recently been investigating issues relating to this, and I can say in the first example posted by @SeniorPlayer that gopher lua does correctly manage the memory and it is garbage collected by the go runtime.
If you run:
> GODEBUG=gctrace=1 ./glua test.lua
Then you will see that after a couple of minutes the go "scavenger" will kick in and start to (very slowly) release the gc-ed memory back to the system. After about 25 minutes all the memory has been released back to the system.

In the second example posted by @epikur-io there was a memory leak in gopher-lua which was stopped the go-gc from reclaiming the tables. By coincidence, I was already fixing this very issue and I can confirm that with my fix this second script also will eventually free all its memory back to the system without running neither `collectgarbage` nor `gos.freeosmem`.
