### ISSUE TITLE
Hope to load file using http.FileSystem

### ISSUE THREAD

**Issue by divanodestiny** [yuin/gopher-lua#228]
gopher-lua load file using `os.Open` now. 
So i think it will be more useful to load file using the `http.FileSystem` implement, like `http.Dir`,  add func to set the filesystem implement so that it could support some static package lib like `packr` or `vfsgen`

**Comment by yuin** [comment]
You can replace `load*` and `require` function with your own code.
`func (ls *LState) Load(reader io.Reader, name string) (*LFunction, error)` may do the job.

**Comment by yuin** [comment]
I've closed the issue due to inactivity. Feel free to reopen the issue if you have any problems.
