### ISSUE TITLE
how to get args in my lua file

### ISSUE THREAD

**Issue by soulbird** [yuin/gopher-lua#229]
I have a lua file，it‘s just a lua chunk and have no function, like this:
//a.lua
```lua
local a = 1
print(a)
--print(arg)
```
and my go code like this: 
```golang
fn, err := L.Load(strings.NewReader(content), name)
if err != nil {
    return nil, err
}

//return L.PCall(0, lua.MultRet, nil)
err = L.CallByParam(lua.P{
    Fn:      fn,
    NRet:    1,
    Protect: true,
}, args...)
```
and I want to know how can I get the args in my lua file. In fact, I can do this by a go function which can be called by lua file, like this: 
```lua
local mm = require "mm"
local args = mm.get_args()
```
Is it have other inner way to do this?

**Comment by yuin** [comment]
In Lua, arguments for a file is assigned to the `args` global variable.

You can set `args` using `LState#SetGlobal` when calling a file as a function.

**Comment by yuin** [comment]
I've closed the issue due to inactivity. Feel free to reopen the issue if you have any problems.
