### ISSUE TITLE
Sandbox and Memory Limit

### ISSUE THREAD

**Issue by phenrigomes** [yuin/gopher-lua#230]
Hey guys! I have searched for a good package to run scripts in my project. I think this module is the better that I found.

I saw the options for Lua State: CallStackSize and RegistrySize. I understand the CallStackSize, but not RegistrySize, if one can help me, it will be very good. Thanks!

I need to know if gopher-lua can limit the memory use. I saw about the allocator for Lua State, but I dont know about if it can be configured on gopher-lua.

So, my questions are:

- What does RegistrySize mean?
- Can I set memory limit?
- Can I set cpu cycle limits?
- Is the LState a safety sandbox for external scripts?

These questions very important for me. Thanks!

**Comment by yuin** [comment]
- What does RegistrySize mean?

RegistrySize roughly means total number of named variables.

- Can I set memory limit?

No. You can set RegistrySize, but unnamed value(i.e. values in the table) can not be handled.

- Can I set cpu cycle limits?

GopherLua can have a context.  [Terminating a running LState](https://github.com/yuin/gopher-lua#terminating-a-running-lstate)

- Is the LState a safety sandbox for external scripts?

See #27 .

**Comment by yuin** [comment]
I've closed the issue due to inactivity. Feel free to reopen the issue if you have any problems.
