### ISSUE TITLE
How could I run a compiled Bitcode？

### ISSUE THREAD

**Issue by Satone7** [yuin/gopher-lua#231]
Hello everyone, I am learning and using GopherLua recently, it is really great. However, I encountered a problem in my project, I could not find the answer, I hope someone can point to the maze.

For example, using "luac -o main.out mian.lua", then how should I use the "main.out" load to run on "gopher-lua", or how to save and generate a "*lua.FunctionProto" object from a file?

Thank you for your consideration for this！

So my questions are:
- how should I use the "main.out" load to run on "gopher-lua"?
- how to save and generate a "*lua.FunctionProto" object from a file?

**Comment by yuin** [comment]
You can not run compiled bytecodes.
GopherLua uses some extra ope codes to optimize in Go environment. Thus GopherLua opecodes is not compatible with original Lua opecodes.

And you can neither save nor generate function proto objects. GopherLua considers bytecodes as completely intermediate representations. Thus it maybe changes, so it should not be saved.
If you need to compile files many time for sharing lua codes between goroutines, you can use [`NewFunctionFromProto`](https://github.com/yuin/gopher-lua#sharing-lua-byte-code-between-lstates) to copy functions.

**Comment by Satone7** [comment]
Ok, thank you for your reply and suggestions~

**Comment by drauschenbach** [comment]
@yuin I'd like to have a discussion about the possibility of Lua bytecodes support. Could you contact me through email please? Thank you! david@nubix.io

**Comment by yuin** [comment]
@drauschenbach This topic has been repeated many times. As I described above, I do not intend to support bytecodes.
