### ISSUE TITLE
difference between while/for for a iterator that uses coroutine yield

### ISSUE THREAD

**Issue by akrpic77** [yuin/gopher-lua#233]
Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : 8bfc7677f583b35a5663a9dd934c08f3b5774bbb
2. What version of Go are you using? : 
go1.12
3. What operating system and processor architecture are you using? :
linux/amd64
4. What did you do? :
for loop using iterator factory that contains closure with coroutine.yield
5. What did you expect to see? :
coroutine.yield to cause to return go's Resume with ResumeYield
6. What did you see instead? :
Resume returned with ResumeOK

It does work if I replace loop with while. 

Please see  #232 for additional tesets in state_test.go. Tests fail for test_with_for where ResumeYield is expected and final result that should be LNil but is "next".

**Comment by yuin** [comment]
`for` and `while` is completely different in Lua. Have you tried same code in original Lua?
Your `test_with_for` function will produces an error like `attempt to yield across metamethod/C-call boundary` .
