### ISSUE TITLE
How to handle escaping

### ISSUE THREAD

**Issue by wenchangshou2** [yuin/gopher-lua#235]
I want to call os.execute to disable the service, and the service name has a space, so I can't execute it correctly.
``` lua
func Test_lua(t *testing.T) {

	L := lua.NewState()
	defer L.Close()
	if err := L.DoString(`
	os.execute("net stop zoolon-Daemon")
	os.execute("net stop \"Zoolon Daemon Service\"")
	os.execute("sc config \\"Zoolon Daemon Service\\" start= disabled")
		`); err != nil {
		t.Error()
		panic(err)
	}
}
```

**Comment by yuin** [comment]
GopherLua uses `os.StartProcess` to create child process. You seems running into this issue( https://github.com/golang/go/issues/15566). <https://github.com/otm/gluash> might be helpful for you.
