### ISSUE TITLE
gmatch unit test failing

### ISSUE THREAD

**Issue by tul** [yuin/gopher-lua#237]
- [X] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [X] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : 8bfc7677f583b35a5663a9dd934c08f3b5774bbb
2. What version of Go are you using? : go version go1.12.1 darwin/amd64
3. What operating system and processor architecture are you using? : macOS
4. What did you do? : `make test`
5. What did you expect to see? : All tests pass
6. What did you see instead? :

````
testing _glua-tests/strings.lua
--- FAIL: TestGlua (0.04s)
    script_test.go:76: issues.lua:180: '[' can not be nested at 0
        stack traceback:
        	[G]: in function 'gmatch'
        	issues.lua:180: in main chunk
        	[G]: ?
````

The failing code is in `issues.lua`

```
local s = [=[["a"]['b'][9] - ["a"]['b'][8] > ]=]
local result = {}
for i in s:gmatch([=[[[][^%s,]*[]]]=]) do 
  table.insert(result, i)
end
assert(result[1] == [=[["a"]['b'][9]]=])
assert(result[2] == [=[["a"]['b'][8]]=])
```

There is something wrong with the pattern being passed to `gmatch`, but I don't know enough about what this is trying to test to fix it.

**Comment by yuin** [comment]
I'm afraid I can't reproduce the error you're seeing.
Current master branch passes all tests( [travis builds](https://travis-ci.org/yuin/gopher-lua) ).

This error still occurs in your environment?

**Comment by tul** [comment]
Yes, it occurs on latest `master` `1a8ee404b9af53cb3e1d461f50a589d776e95375` for me. I suspect it is a macOS only issue.

I also see a complaint from the invocation of the date tool, as the macOS date tool is different from the GNU/Linux one. I can look into that one and propose a fix, but I don't understand the intent of the gmatch one.

```
> go version
go version go1.12.1 darwin/amd64
> git rev-parse HEAD
1a8ee404b9af53cb3e1d461f50a589d776e95375
> make test
./_tools/go-inline *.go && go fmt . &&  go test
state.go
vm.go
testing _glua-tests/base.lua
testing _glua-tests/coroutine.lua
testing _glua-tests/db.lua
testing _glua-tests/issues.lua
testing _glua-tests/os.lua
date: illegal option -- a
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
testing _glua-tests/table.lua
testing _glua-tests/vm.lua
testing _glua-tests/math.lua
testing _glua-tests/strings.lua
--- FAIL: TestGlua (0.04s)
    script_test.go:76: issues.lua:180: '[' can not be nested at 0
        stack traceback:
        	[G]: in function 'gmatch'
        	issues.lua:180: in main chunk
        	[G]: ?
testing _lua5.1-tests/attrib.lua
testing require

 >>> cannot load dynamic library <<<

nil	nil
+
testing assignments, logical operators, and constructors
+
OK
testing _lua5.1-tests/calls.lua
testing functions and calls
+
+
+
+
OK
testing _lua5.1-tests/closure.lua
testing closures and coroutines
+

 >>> testC not active: skipping yield/hook tests <<<

OK
testing _lua5.1-tests/constructs.lua
testing syntax
+
+
+
+
+
+
OK
testing _lua5.1-tests/events.lua
testing metatables
+
OK
testing _lua5.1-tests/literals.lua
testing scanner
+
+
+
+
+

 >>> pt_BR locale not available: skipping decimal point tests <<<

OK
testing _lua5.1-tests/locals.lua
testing local variables plus some extra stuff
+
OK
testing _lua5.1-tests/math.lua
testing numbers and math lib
100	100	0.01
+
`querytab' nao ativo
OK
testing _lua5.1-tests/sort.lua
testing sort
Sorting 30000 elements in 0.01 sec.
Re-sorting 30000 elements in 0.01 sec.
Invert-sorting other 30000 elements in 0.15 sec., with 459069 comparisons
Sorting 30000 equal elements in 0.01 sec.
OK
testing _lua5.1-tests/strings.lua
testing strings and string library
+
+
+
+
locale not supported
locale not supported
OK
testing _lua5.1-tests/vararg.lua
testing vararg
+
+
OK
testing _lua5.1-tests/pm.lua
testing pattern matching
+
+
+
+
OK
testing _lua5.1-tests/files.lua
+
+
+
+
+
+
test done on 13/05/2019, at 10:14:51
Lua 5.1
-------------------------
thread: 0xc0000ae370
top: 6
function base: 5
return base: 5
local base: 6
0 function: 0xc000221a80
1 function: 0xc000221ac0
2 function: 0xc000221b00
3 function: 0xc000221b00
4 function: 0xc0002b3100
5 function: 0xc0002b3340
-------------------------

-------------------------
thread: 0xc0000ae580
top: 6
function base: 5
return base: 5
local base: 6
0 function: 0xc00034d280
1 function: 0xc00034d2c0
2 function: 0xc00034d300
3 function: 0xc00034d300
4 function: 0xc000221ec0
5 function: 0xc0000a28c0
-------------------------


FAIL
exit status 1
FAIL	github.com/tul/gopher-lua	10.104s
make: *** [test] Error 1
```

**Comment by yuin** [comment]
@tul Thank you for your detailed explanations. As you described, It may be a MacOS only issue. 

I have Windows and Linux environments but do not have any MacOS machines, So It is hard to resolve the issue for me.

But I wonder where the error message "'[' can not be nested" comes from. The message seems only be [here](https://github.com/yuin/gopher-lua/blob/b942cacc89fe49895d145e8b360612a9a51d0423/pm/pm.go#L342). As you can see, these lines are commented out.

**Comment by tul** [comment]
Ah, from looking at the test more, maybe the date failure is actually intended?

**Comment by yuin** [comment]
Yes, `date` should be failed. But gmatch should not be failed.

**Comment by tul** [comment]
> But I wonder where the error message "'[' can not be nested" comes from. The message seems only be here. As you can see, these lines are commented out.

Ah this is my mistake. I was running make test in `$GOROOT/src/github.com/tul/gopher-lua`, which had a `pm.go` with the lines commented out. However, go was including `pm.go` from `$GOROOT/src/github.com/yuin/gopher-lua` which had an earlier revision of `pm.go` which had the lines uncommented. If I run the correct code, everything works.

I think my fork approach is flawed, it looks like should be editing in `$GOROOT/src/github.com/yuin/gopher-lua` and I should just add my repo fork as a remote in there.

Sorry for the false alarm, I will close this issue.
