### ISSUE TITLE
New library announcement: gluaperiphery

### ISSUE THREAD

**Issue by drauschenbach** [yuin/gopher-lua#240]
[gluaperiphery](https://github.com/BixData/gluaperiphery) is a port of [lua-periphery](https://github.com/vsergeev/lua-periphery) to the GopherLua VM.

lua-periphery is:

> A Lua library for peripheral I/O (GPIO, SPI, I2C, MMIO, Serial) in Linux.

**Comment by yuin** [comment]
Thanks, I've added gluaperiphery to the README.
