### ISSUE TITLE
How to add luasql module?

### ISSUE THREAD

**Issue by VieYang** [yuin/gopher-lua#246]
1. What version of GopherLua are you using? :  master-1cd887
2. What version of Go are you using? :  go1.12
3. What operating system and processor architecture are you using? :  ubuntu
4. What did you do? : import luasql in hello.lua
5. What did you expect to see? : connet to db
6. What did you see instead? :  ` module luasql.mysql not found`
7. What's your `hello.lua` code?

```lua
mysql = require "luasql.mysql"

local env  = mysql.mysql()
local conn = env:connect('dbname','dbuser','dbpassword','dbhost')

print(env,conn)
```

**Comment by LaevusDexter** [comment]
https://github.com/tengattack/gluasql
