### ISSUE TITLE
Question about Pop - not a bug

### ISSUE THREAD

**Issue by thomas-tacquet** [yuin/gopher-lua#247]
I have a question about "Pop" purposes, in the README.rst there is only one reference to it in this section : https://github.com/yuin/gopher-lua/blob/master/README.rst#calling-lua-from-go 

But I didn't noticed any call to Pop when retrieving arguments in the documentation or related modules. In my software I use Pop this way everytime I retrieve arguments of my functions : 
```go
argA := L.ToString(1)
argB := L.ToInt(2)
L.Pop(2)

// or : 

top := L.GetTop
// forloop
L.Pop(top)
```

Is it good / bad / required / not required ? Why ? 

I think it can lighten Go's garbage collector's work by reducing heap scan about not reachable variables.

**Comment by yuin** [comment]
GopherLua performs same as original Lua about the stack.
Please refer to [this URL](https://stackoverflow.com/questions/1217423/how-to-use-lua-pop-function-correctly).

Summary:
- pop is not necessary.
- but calling pop avoids unexpected stack growth.

**Comment by thomas-tacquet** [comment]
Thank you for your reply, I'll add a new PR to detail this concern.
