### ISSUE TITLE
how to import a installed library?

### ISSUE THREAD

**Issue by coanor** [yuin/gopher-lua#256]
1. What version of GopherLua are you using? :  
	v0.0.0-20190514113301-1cd887cd7036
2. What version of Go are you using? : 
	go version go1.13.1 linux/amd64
3. What operating system and processor architecture are you using? :
	Ubuntu 18.04.3 LTS (server)

I'm trying to use luarock installed mysql package, it's ok to run this lua code with `$ lua5.1 sql.lua`:

	local luasql = require "luasql.mysql"

	function test(sql)
		env = assert(luasql.mysql())
		con = assert(env:connect("xxxxxxxxxxxxxx", "root", "xxxxxxxx", "1.2.3.4", 3306))

		res = con:execute(sql)
		print(res)

		con:close()
		env:close()
	end

	test("select * from some_table")

But when I run these code within go(part of them):

	var luaCode = `
	local luasql = require "luasql.mysql"

	function test(sql)
		env = assert(luasql.mysql())
		con = assert(env:connect("xxxxxxxxxxxxxx", "root", "xxxxxxxx", "1.2.3.4", 3306))

		res = con:execute(sql)
		print(res)

		con:close()
		env:close()
	end
	`
	...

	if err := l.DoString(luaCode); err != nil {
		panic(err)
	}

	if err := l.CallByParam(lua.P{
		Fn:      l.GetGlobal("test"),
		NRet:    0,
		Protect: true,
	}, lua.LString(`select * from some_table`)); err != nil {
		panic(err)
	}

I got the errors below:

	panic: <string>:2: module luasql.mysql not found:
	        no field package.preload['luasql.mysql']
	        stat ./luasql/mysql.lua: no such file or directory
	        stat /usr/local/share/lua/5.1/luasql/mysql.lua: no such file or directory
	        stat /usr/local/share/lua/5.1/luasql/mysql/init.lua: no such file or directory,
	stack traceback:
	        [G]: in function 'require'
	        <string>:2: in main chunk
	        [G]: ?
	
	goroutine 1 [running]:
	main.main()
	        /path/to/call-lua-with-require.go:28 +0x20d

My question is:

- Is it possible to call 3rd-party packages like this?
- From the error hint, it seems that GopherLua has tried to search the package in system path, how to tell GopherLua where to search them?

**Comment by yuin** [comment]
You can not use this kind of library on GopherLua because GopherLua is impelemented in pure Go.
Libraries including C codes does not work for GopherLua, but pure Lua library should work for GopherLua.
