### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by KamilM1205** [yuin/gopher-lua#258]
1. What version of GopherLua are you using? : c6266f4
2. What version of Go are you using? : go1.13.4 linux/amd64
3. What operating system and processor architecture are you using? : linux/amd64
4. What did you do? : 
```go
func luaSetClick(L *lua.LState) int {
	b := checkButton(L)
	b.Button.Connect("clicked", func() {
		if err := L.CallByParam(lua.P{
			Fn:      L.ToFunction(2),
			NRet:    0,
			Protect: true,
		}, lua.LString("click")); err != nil {
			utils.FatalMessage(err.Error())
		}
	})
	return 1
} 
 ```
5. What did you expect to see? : аction of the called function.
6. What did you see instead? : runtime error: invalid memory address or nil pointer dereference

**Comment by epikur-io** [comment]
Does this produce the same error when using `L.CheckFunction(2)` instead of "ToFunction"?

**Comment by KamilM1205** [comment]
@epikur-io Yes it causes an error.

**Comment by tul** [comment]
When does the function you are passing to `Connect` get called? If it gets called after `luaSetClick` has returned then you'll need to grab your function (`L.ToFunction(2)`) outside of the callback, as the stack will be cleared when `luaSetClick` returns.

Try

```
func luaSetClick(L *lua.LState) int {
	b := checkButton(L)
        f := L.ToFunction(2)
	b.Button.Connect("clicked", func() {
		if err := L.CallByParam(lua.P{
			Fn:     f,
			NRet:    0,
			Protect: true,
		}, lua.LString("click")); err != nil {
			utils.FatalMessage(err.Error())
		}
	})
	return 1
} 
```

**Comment by KamilM1205** [comment]
I tried to do it, but this doesn't work for me. I don't know what I can do. (ノ｀Д´)ノ彡┻━┻

**Comment by tul** [comment]
Please can you give more info on the error you get from running my version above,  is it still a memory error? Can you post the stack?

Things to check:
* Are you accessing the same LState from multiple go routines at the same time?
* Is your callback being called after the LState has been closed?

**Comment by KamilM1205** [comment]
Thank you so much!! You just saved me! The problem was that I was trying to call a function while I was already closing LState.(◔‿◔)
