### ISSUE TITLE
runtime panic handling

### ISSUE THREAD

**Issue by AllenDang** [yuin/gopher-lua#274]
- [ x ] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [ x ] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : v0.0.0-20191220021717-ab39c6098bdb
2. What version of Go are you using? :  1.14
3. What operating system and processor architecture are you using? : MacOS v10.15.3
4. What did you do? : Call a none existing method of passing Go object.
5. What did you expect to see? : luaState.DoFile returns a error.
6. What did you see instead? : panic occurred which cause main executable crash

**Comment by humphrycc** [comment]
Can you share your code? Because of `DoFile` calls [`PCall`](https://github.com/yuin/gopher-lua/blob/master/auxlib.go#L394) which [`defer` `recover()`](https://github.com/yuin/gopher-lua/blob/ab39c6098bdba5b34ac9a025d375d4cf5bed4814/state.go#L1969) for panic, I think `DoFile` will not cause panic.

**Comment by AllenDang** [comment]
@humphrycc I'm trying to repo this in minimal code. I'll feed back later.
