### ISSUE TITLE
lua function / golang

### ISSUE THREAD

**Issue by qarasina** [yuin/gopher-lua#277]
1. What version of GopherLua are you using? : Latest
2. What version of Go are you using? : 1.14
3. What operating system and processor architecture are you using? : Windows x64

my code : 

```lua
gm.push("Menu",
function ()
    print("init")
end,
function ()
    print("render")
end,
function ()
    print("update")
end)
```
but, how to get function in params and execute them in go ?

**Comment by humphrycc** [comment]
You can use [`CheckFunction`](https://godoc.org/github.com/yuin/gopher-lua#LState.CheckFunction) or type assertion to get params as [`LFunction`](https://godoc.org/github.com/yuin/gopher-lua#LFunction), and then calls [`CallByParam`](https://godoc.org/github.com/yuin/gopher-lua#LState.CallByParam) to execute it.

**Comment by kwangsing3** [comment]
Hi, Would you mind make a example, plz?


> You can use [`CheckFunction`](https://godoc.org/github.com/yuin/gopher-lua#LState.CheckFunction) or type assertion to get params as [`LFunction`](https://godoc.org/github.com/yuin/gopher-lua#LFunction), and then calls [`CallByParam`](https://godoc.org/github.com/yuin/gopher-lua#LState.CallByParam) to execute it.
