### ISSUE TITLE
can gopher-lua support __gc?

### ISSUE THREAD

**Issue by Hapeng** [yuin/gopher-lua#278]
I prefer to release resource manually when garbage collecting.
So I hope I can use the __gc in metatable. Thanks.

**Comment by humphrycc** [comment]
As gopher-lua is implemented by go, there is no way to gc any special data. Anyway, `collectgarbage` will work but differently, see [Readme](https://github.com/yuin/gopher-lua#miscellaneous-notes).
> `collectgarbage` does not take any arguments and runs the garbage collector for the entire Go program.
