### ISSUE TITLE
Unable to load lua file with include in it

### ISSUE THREAD

**Issue by SaintWish** [yuin/gopher-lua#288]
- [x] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [x] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : master (latest) 
2. What version of Go are you using? : 1.14
3. What operating system and processor architecture are you using? : Windows 10 64 bit
4. What did you do? : Tried to do an include in my Lua file that I loaded.
5. What did you expect to see? : I expected it to load without erroring.
6. What did you see instead? : It threw this error
```
./runtime/lua/autorun.lua:3: attempt to call a non-function object
stack traceback:
        ./runtime/lua/autorun.lua:3: in main chunk
        [G]: ?
```

go file
```
var (
  L *lua.LState
)

func Init() {
  L = lua.NewState()
  if err := L.DoFile("./runtime/lua/autorun.lua"); err != nil {
    fmt.Println("[Error]: ", err)
  }
}

Init()
```
autorun.lua

```
include("blank.lua")
```

blank.lua
```
--print("ya")
```

**Comment by joesonw** [comment]
```go
L.SetGlobal("include", func (L *lua.LState) int {
    newL := lua.NewState()
    err := newL.DoFile(L.CheckString(1))
    if err != nil {
        L.RaiseError(err.Error())
    }
    L.Push(newL.Get(1))
    return 1
})
```

something like this. `gopher-lua` does not come with `include`.
