### ISSUE TITLE
How to get the print result of lua in golang?

### ISSUE THREAD

**Issue by somnmos** [yuin/gopher-lua#290]
1. What version of GopherLua are you using? : 
-- 0.0.0
2. What version of Go are you using? : 
-- 1.12.7
3. What operating system and processor architecture are you using? :
-- ubuntu16.04
4. What did you do? :
-- i want to get the print result of lua in golang, but there is no method to do it using gopherlua. can you give me some suggestion?

**Comment by Fanarito** [comment]
The default `print` function prints straight to stdout. What you could do to get past that is override the print method with your own method. Something like this maybe:
```go
var logs []string
L.SetGlobal("print", L.NewFunction(func(L *lua.LState) int {
	var buf bytes.Buffer
	for i := 1; i <= L.GetTop(); i++ {
		fmt.Fprint(&buf, L.Get(i).String(), " ")
	}
	logs = append(logs, buf.String())
	return 0
}))
```
