### ISSUE TITLE
Support goto statement  in the future? 

### ISSUE THREAD

**Issue by RobinCodeX** [yuin/gopher-lua#311]
I know that Lua5.1 does not support goto statement, but LuaJIT support it.
I'm using [TypeScriptToLua](https://typescripttolua.github.io/) for my project,
The goto statement is required when TypeScriptToLua converts a continue statement into Lua code.
So, Is it possible to implement goto statements?

**Comment by Simerax** [comment]
Gopher-Lua is currently a Lua 5.1 implementation which to me makes it very unlikely that it will be implemented.

There is however a development branch for 5.3 in which goto is already mostly implemented.
See #161 and [this readme](https://github.com/yuin/gopher-lua/tree/5.3/5.3#tasks)
But that Branch is already pretty old so either you:
1. fork and implement it
2. use a different library (maybe https://github.com/milochristiansen/lua)

**Comment by RobinCodeX** [comment]
Ok, thank you.
