### ISSUE TITLE
How get mod filed value?

### ISSUE THREAD

**Issue by lhpy1986** [yuin/gopher-lua#312]
package mymodule

import (
    "github.com/yuin/gopher-lua"
)

func Loader(L *lua.LState) int {
    mod := L.SetFuncs(L.NewTable(), exports)
    L.SetField(mod, "name", lua.LString("value"))
    L.Push(mod)
    return 1
}

var exports = map[string]lua.LGFunction{
    "myfunc": myfunc,
}

func myfunc(L *lua.LState) int {
    //How GET mod fileld name value
    nameval:=mod.GetField()
    return 0
}

**Comment by Simerax** [comment]
It depends on what you are trying to do.
The easiest way with your current setup would be to call the lua function with the module as argument. Like this `mymodule:myfunc()`

Then you can get the first argument (the module table) pretty easily in go.
```go
func myfunc(L *lua.LState) int {
    mod := L.CheckTable(1)
    value := mod.RawGetString("name")
    fmt.Println("--->", value)
    return 0
}
```

**Comment by Simerax** [comment]
@lhpy1986 please close this issue if your problem was resolved
