### ISSUE TITLE
Support Teal

### ISSUE THREAD

**Issue by tooolbox** [yuin/gopher-lua#314]
- [ ] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [x] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : I am using `glua` that I just retrieved via `go get` and it says `GopherLua 0.1 Copyright (C) 2015 -2017 Yusuke Inuzuka` when it starts up.
2. What version of Go are you using? : `go1.15.7`
3. What operating system and processor architecture are you using? : `darwin/amd64`
4. What did you do? : Tried to enable [Teal](https://github.com/teal-language/tl) support by downloading [tl.lua](https://github.com/teal-language/tl/blob/master/tl.lua) and running `local tl = require("tl")` and `tl.loader()`
5. What did you expect to see? : No output, I think?
6. What did you see instead? : An error, as below.

```
GopherLua 0.1 Copyright (C) 2015 -2017 Yusuke Inuzuka
> local tl = require("tl")
> tl.loader()
<string>:1: attempt to index a non-table object(nil) with key 'loader'
stack traceback:
	<string>:1: in main chunk
	[G]: ?
```

I admit that I'm not super familiar with Lua, more with Go, but I'm interested to use Teal in this VM so I'm curious if this is a simple fix or entirely out of the question.

**Comment by tooolbox** [comment]
I played around with this further:

Since `glua` is a repl, seems that declaring something local means it's out of scope in the next command.  So this works:

```lua
tl = require("tl")
tl.loader()
```

In other words, there's no output, no error.  But when I try to use it, there's a failure.  Here's my Teal module, taken from [here](https://teal-playground.netlify.app/?c=LS0gVGVhbCBzdXBwb3J0cyBhIHNpbXBsZSBmb3JtIG9mIGdlbmVyaWNzIHRoYXQgaXMKLS0gdXNlZnVsIGVub3VnaCBmb3IgZGVhbGluZyBjb2xsZWN0aW9ucyBhbmQgYWxnb3JpdGhtcyB0aGF0Ci0tIG9wZXJhdGUgb3ZlciBhYnN0cmFjdCBkYXRhIHR5cGVzLiBZb3UgY2FuIHVzZSB0eXBlCi0tIHZhcmlhYmxlcyB3aGVyZXZlciBhIHR5cGUgaXMgdXNlZCwgYW5kIHlvdSBjYW4gZGVjbGFyZSB0aGVtCi0tIGluIGJvdGggZnVuY3Rpb25zIGFuZCByZWNvcmRzLiBIZXJlJ3MgYW4gZXhhbXBsZSBvZiBhCi0tIGdlbmVyaWMgZnVuY3Rpb246Cgpsb2NhbCBmdW5jdGlvbiBrZXlzPEssVj4oeHM6IHtLOlZ9KTp7S30KICBsb2NhbCBrcyA9IHt9CiAgZm9yIGssIHYgaW4gcGFpcnMoeHMpIGRvCiAgICB0YWJsZS5pbnNlcnQoa3MsIGspCiAgZW5kCiAgcmV0dXJuIGtzCmVuZAoKbG9jYWwgcyA9IGtleXMoeyBhID0gMSwgYiA9IDIgfSkgLS0gcyBpcyB7c3RyaW5nfQ%3D%3D):

```lua
-- keys.tl
local lib = {}

function lib.keys<K,V>(xs: {K:V}):{K}
  local ks = {}
  for k, v in pairs(xs) do
    table.insert(ks, k)
  end
  return ks
end

return lib
```

So then I try to load it:
```lua
> keys = require("keys")
./tl.lua:1427: attempt to index a non-table object(nil) with key 'tk'
stack traceback:
	./tl.lua:1427: in function 'parse_list'
	./tl.lua:1460: in function 'parse_bracket_list'
	./tl.lua:2156: in function 'parse_argument_list'
	./tl.lua:1734: in function 'parse_function_args_rets_body'
	./tl.lua:2244: in function 'parse_statement_fn'
	./tl.lua:2869: in function 'parse_statements'
	./tl.lua:2921: in function 'parse_program'
	./tl.lua:9392: in function <./tl.lua:9383>
	[G]: in function 'require'
	<string>:1: in main chunk
	[G]: ?
```

May just be something strange with `glua` specifically?

**Comment by scrumit** [comment]
I’ve just been reading Tl and it runs on fengari, a JavaScript lua implementation. 

Fengari complies with lua 5.3 and I think Gopher is 5.1

**Comment by rusenask** [comment]
you can't just load files like this in gopher-lua, first you will need to write your own module ant make it available for imports

**Comment by tooolbox** [comment]
> Fengari complies with lua 5.3 and I think Gopher is 5.1

Roger, [I have now asked](https://github.com/teal-language/tl/issues/439) what the minimum version is.

> you can't just load files like this in gopher-lua, first you will need to write your own module ant make it available for imports

Care to elaborate?  From my understanding, Lua modules are just tables of functions.  The Teal source is a good example of this.  I should be able to just `require()` it and then use it, right?

**Comment by hishamhm** [comment]
Hi there, Teal dev here! Teal supports both PUC-Rio Lua 5.1 and LuaJIT. From the looks of the stack trace above, looks like it:

* succeeded loaded the `tl` module
* successfully installed the package loader
* the Teal package loader is running and trying to load `keys.tl` file
* it finished lexing the file (which produces an array of tokens)
* but it is failing halfway through parsing (because it went past the end of the array of tokens).

The above example `keys.tl` parses and loads fine when running Teal with a vanilla PUC-Rio or LuaJIT interpreter, so it looks like it's hitting some issue in the gopher-lua implementation, which caused the array of tokens to be incorrect.

I don't have the environment set up to debug gopher-teal, but I'm happy to answer any questions you folks may have about Teal or its internals. @tooolbox please confirm which version of Teal you're testing with so that everyone is looking at the same `tl.lua`.

**Comment by tooolbox** [comment]
Hey @hishamhm I really appreciate you dropping by.  Would love to get Teal working in Gopher-Lua and therefore [Algernon](https://github.com/xyproto/algernon).

Great on the analysis thus far, and that makes sense.  I suppose I will look around to see what debugging options Gopher-Lua has.  Although, given that this is all happening in Lua, perhaps Teal has some features that could help?  What about just lexing the file and dumping out the tokens, so we can see what Teal is seeing i.e. how many tokens?  Anything you have along those lines would be neat.

I downloaded `tl.lua` straight off the master GitHub branch, so given when I downloaded it, should be https://github.com/teal-language/tl/commit/0da9020cc50fc9db4e270461eb20366fbbb2bd1c although I can use a proper release if you recommend it.

**Comment by hishamhm** [comment]
> What about just lexing the file and dumping out the tokens, so we can see what Teal is seeing i.e. how many tokens? Anything you have along those lines would be neat.

@tooolbox here's a small Lua script I just wrote for that purpose that should let you compare the results between running with `lua` and `glua`:

```lua
local tl = require("tl")

-- read file
local fd = io.open("keys.tl")
local text = fd:read("*a")
fd:close()

-- lexer
local tokens = tl.lex(text)

-- show results
print("------------------------------------")
print("Lexer: " .. #tokens .. " tokens")
print("------------------------------------")
for _, t in ipairs(tokens) do
   print(t.tk, t.kind)
end
print("------------------------------------")

-- parser
local _, ast = tl.parse_program(tokens)

-- show results
print("------------------------------------")
print("Parse tree: ")
print("------------------------------------")
local function recurse(node, indent)
   indent = indent or ""
   print(indent .. node.kind)
   for _, child in pairs(node) do
      if type(child) == "table" and child.kind then
         recurse(child, indent .. "  ")
      end
   end
end
recurse(ast)
print("------------------------------------")
```

**Comment by tooolbox** [comment]
Sorry for the delay.  Tried out the script, here's the output:

```bash
> glua ./teal-test.lua
------------------------------------
Lexer: 32 tokens
------------------------------------
local	keyword
str	identifier
<	op
const	identifier
>	op
=	op
{	{
}	}
function	keyword
str	identifier
.	.
esc_char	identifier
(	(
c	identifier
:	:
string	identifier
)	)
:	:
string	identifier
return	keyword
"%"	string
..	op
c	identifier
end	keyword
return	keyword
{	{
str	identifier
=	op
str	identifier
,	,
}	}
$EOF$	$EOF$
------------------------------------
./tl.lua:1427: attempt to index a non-table object(nil) with key 'tk'
stack traceback:
	./tl.lua:1427: in function 'parse_list'
	./tl.lua:1460: in function 'parse_bracket_list'
	./tl.lua:2156: in function 'parse_argument_list'
	./tl.lua:1734: in function 'parse_function_args_rets_body'
	./tl.lua:2244: in function 'parse_statement_fn'
	./tl.lua:2869: in function 'parse_statements'
	./tl.lua:2921: in function 'parse_program'
	./tt.lua:21: in main chunk
	[G]: ?
```

So it looks like lexing is fine, parsing is not so happy.

**Comment by tooolbox** [comment]
After many inserted debug print statements, I have found that Glua does not like this bit of `parse_argument`:

```lua
if node then
         i, node.decltype = i, decltype
end
```

It results in `i` containing `decltype`.  I changed it to this:

```lua
if node then
         i = i -- necessary?
         node.decltype = decltype
end
```

Now it yields this output:

```bash
------------------------------------
Parse tree:
------------------------------------
statements
  local_declaration
    variable_list
      identifier
    expression_list
      table_literal
  record_function
    type_identifier
    identifier
    argument_list
      argument
    statements
      return
        expression_list
          op
            string
            variable
  return
    expression_list
      table_literal
        table_item
          string
          variable
```

**Comment by hishamhm** [comment]
> Looks like Glua has an issue with generic a, b = c, d multi-assignment, as opposed to when assigning multiple return values from a function?

That's what it sounds like, since that construct is definitely valid Lua (you're right that the multi-assignment there wasn't necessary, but I kept it for symmetry with other parts of the code). Looks like you uncovered a bug in glua — it would probably be a good idea to produce a minimal reproduction case (does it always misbehave on multiple assignments? only when the same variable appears on both sides?) and open a separate issue to get it fixed, perhaps?

**Comment by tooolbox** [comment]
> That's what it sounds like, since that construct is definitely valid Lua (you're right that the multi-assignment there wasn't necessary, but I kept it for symmetry with other parts of the code). Looks like you uncovered a bug in glua — it would probably be a good idea to produce a minimal reproduction case (does it always misbehave on multiple assignments? only when the same variable appears on both sides?) and open a separate issue to get it fixed, perhaps?

Yeah, will put together a minimal repro and open a separate issue.  From testing in the Glua repl, it's not an issue with plain multi-assignment; it handles that properly.  My next guess is assigning to a "property" as part of a multi-assignment, so that's what I'll pursue.

**Comment by tooolbox** [comment]
Okay, filed a bug on that.  In the meantime I'm using my patched version of Teal, here's the next hurdle:

```
GopherLua 0.1 Copyright (C) 2015 -2017 Yusuke Inuzuka
> tl = require("tl")
> tl.loader()
> keys = require("keys")
./tl.lua:9410: bad argument #1 to load (function expected, got string)
stack traceback:
	[G]: in function 'load'
	./tl.lua:9410: in function <./tl.lua:9384>
	[G]: in function 'require'
	<string>:1: in main chunk
	[G]: ?
```

The line in question (since the line numbers are different in my Teal script now) is:

```lua
local function tl_package_loader(module_name)
    -- ...
    local chunk, err = load(code, module_name, "t") --  <= this one
    -- ...
end
```

Looking at the Gopher-Lua source, it looks like the [load function implementation](https://github.com/yuin/gopher-lua/blob/ee81675732da08c6c96265e65c88ef410081bfc0/baselib.go#L33) expects [a function as the first param](https://github.com/yuin/gopher-lua/blob/ee81675732da08c6c96265e65c88ef410081bfc0/baselib.go#L171).

Per [the manual](http://www.lua.org/manual/5.1/manual.html#pdf-load), `load` takes a function, whereas `loadstring` takes a string.  I don't know C well enough to comprehend the sorcery occurring in the [canonical implementation](https://www.lua.org/source/5.1/lapi.c.html#lua_load), or to even be sure I'm looking at the right function, but it seems like it handles a string as well as a function, in defiance of the manual?  It must, based on Teal's source.

I guess the question is whether Teal should change to `loadstring()` or Gopher-Lua should make its `load()` implementation more flexible.  I'm guessing the former would be more correct, thoughts @hishamhm ?

**Comment by tooolbox** [comment]
Ah, Teal is using the [Lua 5.3 implementation](https://www.lua.org/manual/5.3/manual.html#pdf-load) of `load()`.  Not sure what the best route forward here is.

**Comment by tooolbox** [comment]
Successfully got Teal (modified to sidestep that multi-assignment bug) working using compat52 (with the string.dump call removed) and a pure-lua bit32 replacement.

```lua
require("compat52")
tl = require("tl")
tl.loader()
calc = require("calc") -- calc.tl
calc.add(1, 2) -- 3
```

The blockers for straightforward usage are mainly #315 and #336
