### ISSUE TITLE
Multiplication by 10 does not return correct value

### ISSUE THREAD

**Issue by og3og** [yuin/gopher-lua#321]
Hello,

I am trying to do multiplication by 10 on a float and it is returning the incorrect value. 
```
package main

import (
	"github.com/yuin/gopher-lua"
)

func main()  {
	L := lua.NewState()
	defer L.Close()
	if err := L.DoString(`print(42.98 * 10)`); err != nil {
		panic(err)
	}
}
```

1. What version of GopherLua are you using? : 
5.1
2. What version of Go are you using? : 
1.16.3
3. What operating system and processor architecture are you using? :
macOS 11.3
4. What did you do? :
Trying to do a multiplication `print(42.98 * 10)`
5. What did you expect to see? :
The value should be `429.8`
6. What did you see instead? :
Value is `429.79999999999995`

**Comment by og3og** [comment]
I was able to get this working by doing the following 
```
	if err := L.DoString(`print(string.format("%.2f", 42.98 * 10))`); err != nil {
		panic(err)
	}
```

**Comment by AlexanderYastrebov** [comment]
https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems
