### ISSUE TITLE
coroutine can't yield after a require call

### ISSUE THREAD

**Issue by thinkerfei** [yuin/gopher-lua#33]
I have a simple test:

--test.lua
local a,b

a = function ()
	require "inityx_dtba"
	print("a")
	coroutine.yield()
	b()
end 

b = function ()
   print("b")
end 

local co = coroutine.create(a)
local ok = coroutine.resume(co)
while ok  do
	ok = coroutine.resume(co)
end 

It's ok in clua5.1, but when run in glua, I got these error info 
It's very important for me to load module in coroutine, how can solve this issue?

[G]: can not yield from outside of a coroutine
stack traceback:
        [G]: in yield
        test.lua:11: in main chunk
        [G]: ?
goroutine 1 [running]:
github.com/yuin/gopher-lua.func·007()
        e:/fei/go/src/github.com/yuin/gopher-lua/state.go:1365 +0x17e
github.com/yuin/gopher-lua.func·010()
        e:/fei/go/src/github.com/yuin/gopher-lua/vm.go:118 +0x1a2
github.com/yuin/gopher-lua.func·002(0xc082014410)
        e:/fei/go/src/github.com/yuin/gopher-lua/coroutinelib.go:75 +0x72
github.com/yuin/gopher-lua.(*LState).raiseError(0xc082014410, 0x1, 0x650570, 0x2
9, 0x0, 0x0, 0x0)
        e:/fei/go/src/github.com/yuin/gopher-lua/state.go:354 +0x364
github.com/yuin/gopher-lua.(*LState).RaiseError(0xc082014410, 0x650570, 0x29, 0x
0, 0x0, 0x0)
        e:/fei/go/src/github.com/yuin/gopher-lua/state.go:1065 +0x6a
github.com/yuin/gopher-lua.switchToParentThread(0xc082014410, 0x0, 0xc0820d0000)

        e:/fei/go/src/github.com/yuin/gopher-lua/vm.go:44 +0x71
github.com/yuin/gopher-lua.callGFunction(0xc082014410, 0x0, 0xc082006dc0)
        e:/fei/go/src/github.com/yuin/gopher-lua/vm.go:74 +0xe6
github.com/yuin/gopher-lua.func·033(0xc082014410, 0xc070000201, 0x0, 0x0)
        e:/fei/go/src/github.com/yuin/gopher-lua/vm.go:493 +0x22c
github.com/yuin/gopher-lua.mainLoop(0xc082014410, 0x0)
        e:/fei/go/src/github.com/yuin/gopher-lua/vm.go:27 +0x119
github.com/yuin/gopher-lua.threadRun(0xc082014410)
        e:/fei/go/src/github.com/yuin/gopher-lua/vm.go:122 +0x96
github.com/yuin/gopher-lua.coResume(0xc0820143c0, 0x0)
        e:/fei/go/src/github.com/yuin/gopher-lua/coroutinelib.go:82 +0x450
github.com/yuin/gopher-lua.callGFunction(0xc0820143c0, 0x0, 0xc082006e00)
        e:/fei/go/src/github.com/yuin/gopher-lua/vm.go:67 +0x40
github.com/yuin/gopher-lua.func·033(0xc0820143c0, 0xc0700c0402, 0x0, 0x0)
        e:/fei/go/src/github.com/yuin/gopher-lua/vm.go:493 +0x22c
github.com/yuin/gopher-lua.mainLoop(0xc0820143c0, 0x0)
        e:/fei/go/src/github.com/yuin/gopher-lua/vm.go:27 +0x119
github.com/yuin/gopher-lua.(*LState).callR(0xc0820143c0, 0x0, 0xffffffffffffffff
, 0x0)
        e:/fei/go/src/github.com/yuin/gopher-lua/state.go:712 +0x21f
github.com/yuin/gopher-lua.(*LState).Call(0xc0820143c0, 0x0, 0xffffffffffffffff)

        e:/fei/go/src/github.com/yuin/gopher-lua/state.go:1348 +0x4c
github.com/yuin/gopher-lua.(*LState).PCall(0xc0820143c0, 0x0, 0xffffffffffffffff
, 0x0, 0x0, 0x0)
        e:/fei/go/src/github.com/yuin/gopher-lua/state.go:1396 +0x15b
github.com/yuin/gopher-lua.(*LState).DoFile(0xc0820143c0, 0xc0820021f0, 0x8, 0x0
, 0x0)
        e:/fei/go/src/github.com/yuin/gopher-lua/auxlib.go:385 +0xec
main.main()
        e:/fei/go/src/github.com/yuin/gopher-lua/cmd/glua/glua.go:89 +0x769

**Comment by yuin** [comment]
fixed in 58649089d0681e292b152d16d3542fd5c9ba2ecd
