### ISSUE TITLE
Why return error's value is 'true'??

### ISSUE THREAD

**Issue by wwhai** [yuin/gopher-lua#345]
- [ ] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [ ] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : 
```
v0.0.0-20210529063254-f4c35e4016d9
```
2. What version of Go are you using? : 
```
1.7
```

3. What operating system and processor architecture are you using? :
```
ubuntu 20.04 \ windows
```
4. What did you do? :
```
state, err, lValues := vm.Resume(coroutine, callable, args...)
```
5. What did you expect to see? :
```
err is error instead of 'true'
```
6. What did you see instead? :
```
err's value is 'true'
```
![image](https://user-images.githubusercontent.com/20577297/136363190-e4d4dfb3-14f4-417a-b7b9-be126c91f1ac.png)

**Comment by waschik** [comment]
Could you add some more context what is the problem and write the code as text and not as screenshot?

I tried to embed code a simple program:
```go
package main

import (
	"errors"
	"fmt"
	"github.com/yuin/gopher-lua"
)

func run(vm *lua.LState, coroutine *lua.LState, callable *lua.LFunction, args ...lua.LValue) ([]lua.LValue, error) {
	state, err, lValues := vm.Resume(coroutine, callable, args...)
	if state == lua.ResumeError {
		fmt.Println("state:", state)
		return nil, errors.New("current state is not lua.ResumeOK:" + err.Error())
	}
	if state == lua.ResumeOK {
		// only need T
		return lValues[0:2], nil
	}
	return nil, fmt.Errorf("Invalid state: %d", state)
}

func main() {
	vm := lua.NewState()
	defer vm.Close()

	fn, err := vm.LoadString(`
           error("Test")
           return 1, 2
        `)
	if err != nil {
		panic(err)
	}

	coroutine, _ := vm.NewThread()

	_, err = run(vm, coroutine, fn, lua.LNumber(1))
	if err != nil {
		fmt.Printf("Error: %v\n", err)
	}
}
```

Output is:
```
state: 2
Error: current state is not lua.ResumeOK:<string>:2: Test
```

The "2" is the value of lua.ResumeError. So if the `if` matches the Println should always print 2.

**Comment by wwhai** [comment]
> Could you add some more context what is the problem and write the code as text and not as screenshot?
> 
> I tried to embed code a simple program:
> 
> ```go
> package main
> 
> import (
> 	"errors"
> 	"fmt"
> 	"github.com/yuin/gopher-lua"
> )
> 
> func run(vm *lua.LState, coroutine *lua.LState, callable *lua.LFunction, args ...lua.LValue) ([]lua.LValue, error) {
> 	state, err, lValues := vm.Resume(coroutine, callable, args...)
> 	if state == lua.ResumeError {
> 		fmt.Println("state:", state)
> 		return nil, errors.New("current state is not lua.ResumeOK:" + err.Error())
> 	}
> 	if state == lua.ResumeOK {
> 		// only need T
> 		return lValues[0:2], nil
> 	}
> 	return nil, fmt.Errorf("Invalid state: %d", state)
> }
> 
> func main() {
> 	vm := lua.NewState()
> 	defer vm.Close()
> 
> 	fn, err := vm.LoadString(`
>            error("Test")
>            return 1, 2
>         `)
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	coroutine, _ := vm.NewThread()
> 
> 	_, err = run(vm, coroutine, fn, lua.LNumber(1))
> 	if err != nil {
> 		fmt.Printf("Error: %v\n", err)
> 	}
> }
> ```
> 
> Output is:
> 
> ```
> state: 2
> Error: current state is not lua.ResumeOK:<string>:2: Test
> ```
> 
> The "2" is the value of lua.ResumeError. So if the `if` matches the Println should always print 2.

Thanks, I have resolved and this issue was outdated, It will be closed.
