### ISSUE TITLE
Golua compatibillity?

### ISSUE THREAD

**Issue by Splizard** [yuin/gopher-lua#35]
Can gopher-lua be made API compatible with [golua](https://github.com/aarzilli/golua)?
The reason I ask is that it would be very nice to have [Luar](https://github.com/stevedonovan/luar) working with this!

**Comment by yuin** [comment]
> Can gopher-lua be made API compatible with golua?

No.

> The reason I ask is that it would be very nice to have Luar working with this!

You can use [gopher-luar](https://github.com/layeh/gopher-luar).

**Comment by Splizard** [comment]
alright thanks :) gopher-luar looks nice too
