### ISSUE TITLE
Is there any ways to prevent go application from being killed when using os.Exit

### ISSUE THREAD

**Issue by ghost** [yuin/gopher-lua#358]
Is there any ways to prevent go application from being killed when using os.Exit
go language have goroutine and can't make a own multiprocess system
so it may be better if os.Exit kills only lua application

**Comment by gnarfel** [comment]
simply redefine os.exit in your program.  either:

LuaState.DoString("os.exit = nil")

or crawl the table using GetGlobal and GetField or whatever and replace it that way.
