### ISSUE TITLE
Possible stack issue

### ISSUE THREAD

**Issue by otm** [yuin/gopher-lua#37]
I discovered this when I was integrating gopher-lua and I'm able to reproduce it with glua as well. To work around the issue I had to assign the `string.format` to a temporary variable and then do the `var1 = var1 or var2` statement. 

### test.lua
``` lua
function test(a, b, c)
	b = b or string.format("test %v", a)
	c = c or string.format("test %v", a)

	print("a:", a)
	print("b:", b)
	print("c:", c)
end
```

### Run
```
glua test.lua hello
``` 

### Expected result:
```
a:	hello
b:	test hello
c:	test hello
```

### Actual result:
```
a:	hello
b:	test hello
c:	test %v
```

**Comment by otm** [comment]
:star: Thanks mate! That was a quick patch. Both Lua and my code work as expected now. 

For reference: https://github.com/otm/blade

**Comment by yuin** [comment]
No worries mate. Thank you for your contribution.
