### ISSUE TITLE
Non-latin characters not working in regular expressions

### ISSUE THREAD

**Issue by Zero3** [yuin/gopher-lua#39]
I'm writing a plugin for [Piepan](https://github.com/layeh/piepan) which uses gopher-lua for its Go Lua plugins. I use `string.match()` in such a plugin with a regular expression to sanitize user input. However, this does not work with non-latin characters such as the Danish `æ`, `ø` and `å`. Regular expression implementations usually support this.

A trivial example:

    print(string.match("abc", "abc"))
    abc

    print(string.match("æøå", "æøå"))
    nil

Is this a bug in gopher-lua? Or do I need to do something special to be able to use these non-latin characters?

(I originally filed this bug against Piepan here: https://github.com/layeh/piepan/issues/31. The author sent me here.)

**Comment by yuin** [comment]
GopherLua does not support non-latin characters in the pattern match so far.
I added a non-latin character support for this issue.
Please give it a try.

**Comment by Zero3** [comment]
I just rebuilt Piepan and it appears to work now! Thanks a lot!
