### ISSUE TITLE
Call Go from Lua

### ISSUE THREAD

**Issue by jsimnz** [yuin/gopher-lua#4]
I started playing with this library, and have really liked it so far. Except for this annoying method of creating Go funcs that can be called from Lua. Its been constructed that you have to write these methods with the lua state in mind.

I have written a proof on concept function that essentially replaces LState.NewFunction with an interface{} that is typed checked to ensure it has been passed a function, then essentially does some reflection magic to automatically get all the required arguments from the state in their proper types, call the function with the arguments, and push any and all of the results back onto the stack in their respective orders.

Heres an example

```
func Double(i int) int {
    return i * 2
}

func main() { 
	L := lua.NewState()
	defer L.Close()
	L.SetGlobal("double", L.NewFunc(Double)) /* wraps Double and called newLFunction */
}
```

If this is something that you'd accept into the codebase I will finish my implementation, currently it only works with ints as arguments and returns (Not for any particular purpose, I just chose a type to test with)

**Comment by funny-falcon** [comment]
main gopherlua's feature is performance imho, sand any reflection magic will hurt it.

If don't concern about performance, then you can use custom wrapper with reflection magic.

**Comment by jsimnz** [comment]
I'll Run some benchmarks and see what the hit is like.

**Comment by bontibon** [comment]
I am currently working on something similar. It currently has support for most types, including channels, structs, and maps. You can take a look at it here:

https://godoc.org/github.com/layeh/gopher-luar ([github](https://github.com/layeh/gopher-luar))

**Comment by yuin** [comment]
I don't think the performance is main feature of the GopherLua.
(There are many way to make more fast implementations)

My design principles are:

- Integration of Lua's philosophy and Go's philosophy
    - keep it simple
    - perfer scaling back functions than adding new functions
    - no magic
- User friendly Go APIs

That means, in short, it is important that balancing the simplicity with easy-to-use APIs.

The most appropiate approach for the situation is making it as a library.

I think bontibon's gopher-luar is the best for this situation.

**Comment by yuin** [comment]
close this issue for now
