### ISSUE TITLE
【BUG】panic: runtime error: index out of range [1048577] with length 1048577

### ISSUE THREAD

**Issue by wwhai** [yuin/gopher-lua#475]
## Error Info：
```sh
panic: runtime error: index out of range [1048577] with length 1048577
```
The code :
```go
func (rg *registry) Push(v LValue) {
	newSize := rg.top + 1
	// this section is inlined by go-inline
	// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
	{
		requiredSize := newSize
		if requiredSize > cap(rg.array) {
			rg.resize(requiredSize)
		}
	}
	rg.array[rg.top] = v
	rg.top++
}

```

Found when execute ：`rg.array[rg.top] = v` occur the panic。

**Comment by Flosckow** [comment]
@wwhai. 你好! Can you provide a little more detail on how to solve this problem? I keep getting this error while using krakend. 謝謝你！

**Comment by wwhai** [comment]
> @wwhai. 你好! Can you provide a little more detail on how to solve this problem? I keep getting this error while using krakend. 謝謝你！

Sorry ，I have not resolved it。
