### ISSUE TITLE
Problem to Add nested LTable in LTable

### ISSUE THREAD

**Issue by skyhit** [yuin/gopher-lua#49]
When using RawSet function to add a LTable inside another LTable, I got error like 

cannot use *llTable (type lua.LTable) as type lua.LValue in argument to ltable.RawSet: lua.LTable does not implement lua.LValue (String method has pointer receiver)

but I see lua.LTable do implement lua.LValue interface.  any idea?

**Comment by yuin** [comment]
Can I see your code?
Please note that `lua.LTable` is not `*lua.LTable`.

**Comment by skyhit** [comment]
try the following code.

package main
```
import "github.com/yuin/gopher-lua"

func main() {
	L := lua.NewState()
	defer L.Close()
	input := &lua.LTable{}
	input.RawSet(lua.LString("test"), lua.LTable{})
}
```

**Comment by skyhit** [comment]
ok, other than lua.LNumber, lua.LString, we need to pass the pointer, instead of the object.

&lua.LTable{} seems working.
