### ISSUE TITLE
Readme - concurrency.

### ISSUE THREAD

**Issue by andrewchambers** [yuin/gopher-lua#5]
Could you write a readme heading describing how go routines interact with gopher-lua, and what is/isn't thread safe.

**Comment by yuin** [comment]
In short, the LState is not goroutine-safe.  I would recommend to use one LState per goroutine and communicate between goroutines by using channels.

BTW, I am planning to introduce some channel supports into the GopherLua.
I will write a readme about goroutines when the implementation is completed.

**Comment by andrewchambers** [comment]
Thanks for the info.
