### ISSUE TITLE
Weird memory leak

### ISSUE THREAD

**Issue by Raggaer** [yuin/gopher-lua#56]
Im currently running a simple LUA script with a module

```go
func (c *CharacterModule) characterDeaths(L *lua.LState) int {
	name := L.ToString(1)
	deaths, err := models.GetCharacterDeaths(name)
	if err != nil {
		L.Push(lua.LString(err.Error()))
		L.Push(lua.LNil)
		return 2
	}
	death_list := &lua.LTable{}
	for _, val := range deaths {
		t := &lua.LTable{}
		t.RawSetString("time", lua.LNumber(val.Time))
		t.RawSetString("level", lua.LNumber(val.Level))
		t.RawSetString("killed_by", lua.LString(val.Killed_by))
		t.RawSetString("most_damage_by", lua.LString(val.Mostdamage_by))
		death_list.Append(t)
	}
	L.Push(lua.LBool(true))
	L.Push(death_list)
	return 2
}
```

```lua
local character_module = require("character")
local errorx, deaths = character_module.getCharacterDeaths("Kassem G")
if(errorx ~= true) then
    return false
end
local template = {}
template["list"] = {}
template["list"]["killed_by"] = "load test"
return template
```

Im using a http load test tool and at a certain points my app goes from 0-1% CPU usage to 50%
Im doing something wrong while creating the lua table?

Im sure the error is in the getCharacterDeaths function since removing it makes my CPU usage go quiet

Also im sure its not this part

```go
models.GetCharacterDeaths(name)
```

Since I teste that one alone and nothing happened

So maybe im missing something while working with lua tables?

**Comment by yuin** [comment]
```go
t := &lua.LTable{}
```

Instead, Creating new table should be like this:

```go
t := L.NewTable()
```

**Comment by yuin** [comment]
Due to lack of your response I am closing this issue for now.
Please feel free to reopen this issue if you have any questions.
