### ISSUE TITLE
io.read panic

### ISSUE THREAD

**Issue by nubunto** [yuin/gopher-lua#61]
I have the following code:

	package main

	import (
		"github.com/yuin/gopher-lua"
	)

	var luaProgram = `
		-- defines a factorial function
		function fact (n)
		  if n == 0 then
			return 1
		  else
			return n * fact(n-1)
		  end
		end
		
		print("enter a number:")
		a = io.read("*number")        -- read a number
		print(fact(5))
	`

	func main() {
		L := lua.NewState()
		defer L.Close()
		
		if err := L.DoString(luaProgram); err != nil {
			panic(err)
		}
	}

When I run it, I get the following error:

	enter a number:
	15
	panic: <string>:12: bad argument #2 to read (invalid options:u)
	stack traceback:
			[G]: in read
			<string>:12: in function 'main chunk'
			[G]: ?

	goroutine 1 [running]:
	main.main()
			C:/Users/Bruno.Panuto/Desktop/lua.go:27 +0xc7

By using the glua interpreter, I get the same panic.
Using Windows may be the case, but I am just wondering what went wrong.

Thanks!

**Comment by yuin** [comment]
try
```
a = io.read("*n")
```
.

**Comment by nubunto** [comment]
Oh, that worked. Thanks!

Mind if I be curious and ask why the other didn't work?

**Comment by yuin** [comment]
Your example is wrong though it is official, I think.
`*number` is not defeind in the [Reference manual](http://www.lua.org/manual/5.1/manual.html#pdf-file:read) . CLua ignores invalid arguments but GopherLua does not accept such arguments.

**Comment by nubunto** [comment]
I see. Interesting.

Thanks for your help!
