### ISSUE TITLE
debug.traceback: does not support level argument

### ISSUE THREAD

**Issue by bmatsuo** [yuin/gopher-lua#62]
The debug.traceback function does not support the **level** argument as described in the [reference manual](http://www.lua.org/manual/5.1/manual.html#pdf-debug.traceback).

This seems like it would be helpful for writing error handling functions (edit: specifically for use with PCall). As it is now, I think the error handling function is included in any stracktrace the error handling function produces.

**Comment by bmatsuo** [comment]
Wow. That was fast.

It seems to be working well enough in the gluatest framework I put together in my project https://github.com/bmatsuo/lark.

Thanks.

**Comment by yuin** [comment]
No problem.
Please feel free to ask me if you have any questions.
