### ISSUE TITLE
Debug hooks

### ISSUE THREAD

**Issue by bitwalker** [yuin/gopher-lua#69]
Hi! Awesome work on this! I've been prototyping a project which uses gopher-lua to run user-defined scripts in a sandbox, and everything has been going pretty smoothly so far, however I would like to implement some resource constraints on scripts which are run, and based on previous experience, the way this is done is with debug hooks. Is there a specific reason why they are not exposed in gopher-lua? Is it possible to add them? I see that the shopify/go-lua project does implement them, but they are missing other things that gopher-lua has, and as far as I can tell, is not particularly active. Rather than cut over to using shopify/go-lua, I'm wondering if it's feasible to implement the debug hooks in gopher-lua, and wanted to get some background on why they were omitted before I started working on anything.

Thanks!

**Comment by yuin** [comment]
Hi.
Currently, Go is not suitable for implementing **fast** scripting language for some reasons. 
Debug hooks can easily be implemented in GopherLua, but cause a little performance degradation and are be not quite so common(Sandboxing is one of the few exceptions). 
Even if debug hooks are implemented as an option, it will need extra 'if' statements in heavy path on the VM.
So I omitted it to improve performance for common users who do not need debug hooks.

**Comment by bitwalker** [comment]
That makes sense to me 👍 . I may fork and add the hooks, just for the project I'm working on. Would you be able to point me in the right direction on where those should be implemented? I'll be diving in some time today to try and get that done, but it will be the first time I've dived in to the gopher-lua source beyond surface level, and some guidance would be a huge help. Feel free to close this issue either way :)

**Comment by yuin** [comment]
Just off the top of my head...

1. `struct LState` will hold debug functions as fields.
2. `struct LState` will hold a counter for counting function calls
3. You will need to check whether interpreter is about to start the execution of a new line of code and execute hook functions near https://github.com/yuin/gopher-lua/blob/3e406aee054bae285797f8c21785da542c2391c8/_vm.go#L26 (The line hook)
4. You will need to count instructions and execute hook functions near https://github.com/yuin/gopher-lua/blob/3e406aee054bae285797f8c21785da542c2391c8/_vm.go#L26 (The count hook)
5. You will need to execute hook functions near https://github.com/yuin/gopher-lua/blob/3e406aee054bae285797f8c21785da542c2391c8/_vm.go#L503 , L531 and L593(The call hook and The return hook)

I hope that it will be helpful for you.

**Comment by bitwalker** [comment]
That's a great start, thanks!
