### ISSUE TITLE
Loading of modules written in C

### ISSUE THREAD

**Issue by efeller** [yuin/gopher-lua#87]
Looks like cpath is set to empty by default (https://github.com/yuin/gopher-lua/blob/master/loadlib.go). This prevents gopher-lua from finding C modules. I was wondering if there is some good way to make gopher-lua search for modules written in C?

Thanks

**Comment by yuin** [comment]
You are misunderstanding GopherLua implementation.
GopherLua is a Lua implementation that is written in **pure** Go, so GopherLua cannot load C modules.
