### ISSUE TITLE
share a xmlpath libraries for GopherLua

### ISSUE THREAD

**Issue by ailncode** [yuin/gopher-lua#88]
https://github.com/ailncode/gluaxmlpath.git

**Comment by yuin** [comment]
Thanks for your contribution.
I've added your library under "Libraries for GopherLua" .

**Comment by ailncode** [comment]
Thanks and Please give more advice.

**Comment by yuin** [comment]
Your code is idiomatic in GopherLua. Good.
If there's one thing I advise you , it will be better to return [Lua standard iterator](https://www.lua.org/pil/7.1.html) when calling `path:iter(node)` .

**Comment by ailncode** [comment]
Thanks, I‘ve changed it.
