### ISSUE TITLE
How could I terminate a running state?

### ISSUE THREAD

**Issue by frasergraham** [yuin/gopher-lua#89]
I'm trying to execute a user supplied Lua string in a limited environment and i'd like to provide execution time limits. Is there a way for me to terminate a running lua state gracefully? 

I've tried the following....

	f := L.GetGlobal("check")
	env := L.NewTable()
	L.SetFEnv(f, env)
	done := make(chan bool)
	go func() {
		if err = L.CallByParam(lua.P{
			Fn:      f,    // name of Lua function
			NRet:    1,    // number of returned values
			Protect: true, // return err or panic
		}, attr); err != nil {
			log.Println(err)
			return
		}
		// Get the returned value from the stack and cast it to a lua.LBool
		if rc, ok := L.Get(-1).(lua.LBool); ok {
			done <- lua.LVAsBool(rc)
		}

		// Pop the returned value from the stack
		L.Pop(1)
	}()

	select {
	case <-time.After(time.Second):
		// Kill lua func
	case rc := <-done:
		log.Printf("Yay : %v", rc)
	}

where the function "check" should not take more than 1s, if it does I want to kill it, but i'm not sure how, closing the Lua State or raising an error makes it panic, which is undesirable for me.

What is the correct way to terminate execution cleanly?

**Comment by frasergraham** [comment]
I can accomplish this with recover() but it feels wrong...

	select {
	case <-time.After(time.Second * 4):
		// Kill lua func

		go func() {
			defer func() {
				// recover from panic if one occured. Set err to nil otherwise.
				if recover() != nil {
					err = errors.New("Ugh")
				}
			}()

			L.Error(lua.LString("timeout"), 1)
			log.Printf(err.Error())

		}()

	case rc := <-done:
		log.Printf("Yay : %v", rc)
	}

**Comment by frasergraham** [comment]
Actually that didn't work, my test app was exiting before the recover goroutine had run

**Comment by yuin** [comment]
This functionality is supported in Original Lua by the `debug` module . But GopherLua does not have the `debug` module for some reasons(see #69).

You can not terminate a running state without modfying GopherLua core source codes.
You can fork and modify the core codes. #84 might be helpful for you(but performance degradation may occur).

**Comment by frasergraham** [comment]
Are you saying there is no way to shut down or interrupt a LuaState at all? My goal is to prevent user supplied scripts from hitting infinite loops or performing very slow operations, is it not possible to accomplish this with gopher-lua, do I need to use the c implementation?

**Comment by yuin** [comment]
> Are you saying there is no way to shut down or interrupt a LuaState at all?
Yes.

> do I need to use the c implementation?
Yes. Or as I suggested above you can fork GopherLua and merge #84 .

**Comment by yuin** [comment]
@frasergraham , Now I've added a context support GopherLua. Please refer to #84 and README .

**Comment by frasergraham** [comment]
Awesome, thankyou. I can stop using a fork now :)
