### ISSUE TITLE
Add benchmark against agora?

### ISSUE THREAD

**Issue by saward** [yuin/gopher-lua#9]
Hi,

I tested agora (https://github.com/PuerkitoBio/agora/) a year or two ago, and found it much faster than otto.  As a suggestion, I thought you may want a benchmark against that as a comparison, too.

**Comment by yuin** [comment]
As I wrote [here](https://github.com/yuin/gopher-lua/issues/4), I don't think the performance is main feature of the GopherLua.

I am not a professional programmer, I have implemented GopherLua for persornal interest in a register based VM, Lua, and Go.
I did not expect that GopherLua attract a great deal of considerable attention. I regret what I worte about benchmarks.

I plan to copy the benckmark section in the README to the wiki.
You can edit the page freely.

**Comment by yuin** [comment]
I added benchmark results of the agora to the wiki page.
