### ISSUE TITLE
match error : unfinished range at 8

### ISSUE THREAD

**Issue by wllenyj** [yuin/gopher-lua#91]
local str = string.match(url, ".-_([%w-]*)[_.]*")

url si "www.aaa.bbb_abc123-321-cba_abc123"
or "www.aaa.bbb_abc123-321-cba"

xxxxx.lua:xxx: unfinished range at 8

**Comment by yuin** [comment]
I was busy at work and I couldn't get down to this issue.
I've just fixed the issue  with 03a3065 .

**Comment by sakateka** [comment]
Hi, there is still a bug
```bash
~$ lua -e 's = "hello-world"; print(s:match("([^-]+)-world"))'
hello
~$ glua -e 's = "hello-world"; print(s:match("([^-]+)-world"))'
<string>:1: invalid charcter class before '-' at 8
stack traceback:
	[G]: in function 'match'
	<string>:1: in main chunk
	[G]: ?

```

**Comment by yuin** [comment]
Thasnks, I've fixed it.
