### ISSUE TITLE
Dot '.' in set '[]' are not magic character

### ISSUE THREAD

**Issue by sakateka** [yuin/gopher-lua#92]
- [YES] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [YES] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : GopherLua 0.1
2. What version of Go are you using? :  go version go1.7.4 linux/amd64
3. What operating system and processor architecture are you using? : linux/amd64
4. What did you do? : test string matching
5. What did you expect to see? : captured match
6. What did you see instead? : nothing

```bash
~$ glua -v
GopherLua 0.1 Copyright (C) 2015 Yusuke Inuzuka
~$ lua5.1 -v
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio

~$ # dot in set is not magic character
~$ lua5.1 -e 's = "hello.world"; print(s:match("([^.]+).world"))' 
hello
~$ glua -e 's = "hello.world"; print(s:match("([^.]+).world"))'

~$ # explicit escaping
~$ glua -e 's = "hello.world"; print(s:match("([^%.]+).world"))'
hello
~$ lua5.1 -e 's = "hello.world"; print(s:match("([^%.]+).world"))'
hello
```
reference manual https://www.lua.org/manual/5.1/manual.html#5.4 say, **All classes `%x` described above can also be used as components in set** , so dot not starts with `%` therefore not match this rule

**Comment by yuin** [comment]
I was busy at work and I couldn't get down to this issue.
I've just fixed the issue  with 03a3065 .
