### ISSUE TITLE
luac support

### ISSUE THREAD

**Issue by Raggaer** [yuin/gopher-lua#93]
Is the support for executing `.luac` files possible?

**Comment by yuin** [comment]
I can, if I have to. But I think it's not worth it.

1. Compilation time accounts for a very small percentage of the total processing time. It means that pre-compiling contributes little to performance.
2. GopherLua bytecodes are **based on** original Lua bytecodes, but optimized for Go. Thus GopherLua bytecodes are used only as internal representations and may be changed.
3. Security. It is almost impossible to find malicious code in pre-compiled byte codes.

**Comment by Raggaer** [comment]
I was finding a way to make closed-sourced plugins for a system I was working on.

But I understand its not worth it. Also there are multiple decompilers out there for lua so my point its dead too.

Thanks
