### ISSUE TITLE
Pooling problems

### ISSUE THREAD

**Issue by Raggaer** [yuin/gopher-lua#98]
I am using a simple state pool (same as your example) but I am getting values from other pools when calling

`L.Get(-1)`

I sometimes get values from other states of the pool even tho I am calling `L.Pop(-1)` everytime I am done with the state. This is the code I am working with (removed some parts to make it cleaner and shorter)

```go
func executeWidgets(L *glua.LState, tkn *models.CsrfToken) {
	// Create a wait group for the widgets
	wg := &sync.WaitGroup{}

	// State slice
	states := []*glua.LState{}

	// Populate slice of states from the pool
	for i := 0; i < len(util.Widgets.List); i++ {

		// Get a new lua state
		L := Pool.Get()

		// Add state to the slice
		states = append(states, L)
	}

	// Loop all widgets
	for i, widget := range util.Widgets.List {

		// Add a task
		wg.Add(1)

		log.Println(i, states[i].Get(-1))

		// Execute widget to get the result
		go executeWidget(states[i], widget, wg, tkn.Token)
	}

	// Wait for the tasks
	wg.Wait()

	// Loop the states slice
	for _, state := range states {
                state.Pop(-1)
                 
		// Return state to the main pool
		Pool.Put(state)
	}
}
```

`executeWidget` calls `L.DoFile()` and `L.Get(-1)` 

On the `log.Println()` statement. The first time I call this function it always print `nil`. The second time it prints values that were used on the last call...

The error occurs when my lua script does not return anything. Is this intended?

What I am missing?

**Comment by bbuck** [comment]
Can you simplify your problem into something that could be run and tested by others? I'd be interested in helping you but I can't do much with just this function.

**Comment by Raggaer** [comment]
Sorry. I no longer can replicate this. Thanks for the response tho I think it was related to `LFunction` not beeing thread safe!
